// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountproxy"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
)

// AccountProxyCreate is the builder for creating a AccountProxy entity.
type AccountProxyCreate struct {
	config
	mutation *AccountProxyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountProxyCreate) SetAccountID(v int64) *AccountProxyCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetProxyID sets the "proxy_id" field.
func (_c *AccountProxyCreate) SetProxyID(v int64) *AccountProxyCreate {
	_c.mutation.SetProxyID(v)
	return _c
}

// SetConcurrency sets the "concurrency" field.
func (_c *AccountProxyCreate) SetConcurrency(v int) *AccountProxyCreate {
	_c.mutation.SetConcurrency(v)
	return _c
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_c *AccountProxyCreate) SetNillableConcurrency(v *int) *AccountProxyCreate {
	if v != nil {
		_c.SetConcurrency(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *AccountProxyCreate) SetSortOrder(v int) *AccountProxyCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *AccountProxyCreate) SetNillableSortOrder(v *int) *AccountProxyCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountProxyCreate) SetCreatedAt(v time.Time) *AccountProxyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountProxyCreate) SetNillableCreatedAt(v *time.Time) *AccountProxyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountProxyCreate) SetUpdatedAt(v time.Time) *AccountProxyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountProxyCreate) SetNillableUpdatedAt(v *time.Time) *AccountProxyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountProxyCreate) SetAccount(v *Account) *AccountProxyCreate {
	return _c.SetAccountID(v.ID)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_c *AccountProxyCreate) SetProxy(v *Proxy) *AccountProxyCreate {
	return _c.SetProxyID(v.ID)
}

// Mutation returns the AccountProxyMutation object of the builder.
func (_c *AccountProxyCreate) Mutation() *AccountProxyMutation {
	return _c.mutation
}

// Save creates the AccountProxy in the database.
func (_c *AccountProxyCreate) Save(ctx context.Context) (*AccountProxy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountProxyCreate) SaveX(ctx context.Context) *AccountProxy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountProxyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountProxyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountProxyCreate) defaults() {
	if _, ok := _c.mutation.Concurrency(); !ok {
		v := accountproxy.DefaultConcurrency
		_c.mutation.SetConcurrency(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := accountproxy.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountproxy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountproxy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountProxyCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountProxy.account_id"`)}
	}
	if _, ok := _c.mutation.ProxyID(); !ok {
		return &ValidationError{Name: "proxy_id", err: errors.New(`ent: missing required field "AccountProxy.proxy_id"`)}
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		return &ValidationError{Name: "concurrency", err: errors.New(`ent: missing required field "AccountProxy.concurrency"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "AccountProxy.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountProxy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountProxy.updated_at"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountProxy.account"`)}
	}
	if len(_c.mutation.ProxyIDs()) == 0 {
		return &ValidationError{Name: "proxy", err: errors.New(`ent: missing required edge "AccountProxy.proxy"`)}
	}
	return nil
}

func (_c *AccountProxyCreate) sqlSave(ctx context.Context) (*AccountProxy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *AccountProxyCreate) createSpec() (*AccountProxy, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountProxy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountproxy.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Concurrency(); ok {
		_spec.SetField(accountproxy.FieldConcurrency, field.TypeInt, value)
		_node.Concurrency = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(accountproxy.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountproxy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountproxy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountproxy.AccountTable,
			Columns: []string{accountproxy.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountproxy.ProxyTable,
			Columns: []string{accountproxy.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProxyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountProxy.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountProxyUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountProxyCreate) OnConflict(opts ...sql.ConflictOption) *AccountProxyUpsertOne {
	_c.conflict = opts
	return &AccountProxyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountProxy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountProxyCreate) OnConflictColumns(columns ...string) *AccountProxyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountProxyUpsertOne{
		create: _c,
	}
}

type (
	// AccountProxyUpsertOne is the builder for "upsert"-ing
	//  one AccountProxy node.
	AccountProxyUpsertOne struct {
		create *AccountProxyCreate
	}

	// AccountProxyUpsert is the "OnConflict" setter.
	AccountProxyUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountProxyUpsert) SetAccountID(v int64) *AccountProxyUpsert {
	u.Set(accountproxy.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountProxyUpsert) UpdateAccountID() *AccountProxyUpsert {
	u.SetExcluded(accountproxy.FieldAccountID)
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *AccountProxyUpsert) SetProxyID(v int64) *AccountProxyUpsert {
	u.Set(accountproxy.FieldProxyID, v)
	return u
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *AccountProxyUpsert) UpdateProxyID() *AccountProxyUpsert {
	u.SetExcluded(accountproxy.FieldProxyID)
	return u
}

// SetConcurrency sets the "concurrency" field.
func (u *AccountProxyUpsert) SetConcurrency(v int) *AccountProxyUpsert {
	u.Set(accountproxy.FieldConcurrency, v)
	return u
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *AccountProxyUpsert) UpdateConcurrency() *AccountProxyUpsert {
	u.SetExcluded(accountproxy.FieldConcurrency)
	return u
}

// AddConcurrency adds v to the "concurrency" field.
func (u *AccountProxyUpsert) AddConcurrency(v int) *AccountProxyUpsert {
	u.Add(accountproxy.FieldConcurrency, v)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *AccountProxyUpsert) SetSortOrder(v int) *AccountProxyUpsert {
	u.Set(accountproxy.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AccountProxyUpsert) UpdateSortOrder() *AccountProxyUpsert {
	u.SetExcluded(accountproxy.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AccountProxyUpsert) AddSortOrder(v int) *AccountProxyUpsert {
	u.Add(accountproxy.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountProxyUpsert) SetUpdatedAt(v time.Time) *AccountProxyUpsert {
	u.Set(accountproxy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountProxyUpsert) UpdateUpdatedAt() *AccountProxyUpsert {
	u.SetExcluded(accountproxy.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountProxy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountProxyUpsertOne) UpdateNewValues() *AccountProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountproxy.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountProxy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountProxyUpsertOne) Ignore() *AccountProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountProxyUpsertOne) DoNothing() *AccountProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountProxyCreate.OnConflict
// documentation for more info.
func (u *AccountProxyUpsertOne) Update(set func(*AccountProxyUpsert)) *AccountProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountProxyUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountProxyUpsertOne) SetAccountID(v int64) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountProxyUpsertOne) UpdateAccountID() *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateAccountID()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *AccountProxyUpsertOne) SetProxyID(v int64) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *AccountProxyUpsertOne) UpdateProxyID() *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateProxyID()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *AccountProxyUpsertOne) SetConcurrency(v int) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *AccountProxyUpsertOne) AddConcurrency(v int) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *AccountProxyUpsertOne) UpdateConcurrency() *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateConcurrency()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AccountProxyUpsertOne) SetSortOrder(v int) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AccountProxyUpsertOne) AddSortOrder(v int) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AccountProxyUpsertOne) UpdateSortOrder() *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountProxyUpsertOne) SetUpdatedAt(v time.Time) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountProxyUpsertOne) UpdateUpdatedAt() *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountProxyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountProxyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountProxyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// AccountProxyCreateBulk is the builder for creating many AccountProxy entities in bulk.
type AccountProxyCreateBulk struct {
	config
	err      error
	builders []*AccountProxyCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountProxy entities in the database.
func (_c *AccountProxyCreateBulk) Save(ctx context.Context) ([]*AccountProxy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountProxy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountProxyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountProxyCreateBulk) SaveX(ctx context.Context) []*AccountProxy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountProxyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountProxyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountProxy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountProxyUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountProxyCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountProxyUpsertBulk {
	_c.conflict = opts
	return &AccountProxyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountProxy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountProxyCreateBulk) OnConflictColumns(columns ...string) *AccountProxyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountProxyUpsertBulk{
		create: _c,
	}
}

// AccountProxyUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountProxy nodes.
type AccountProxyUpsertBulk struct {
	create *AccountProxyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountProxy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountProxyUpsertBulk) UpdateNewValues() *AccountProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountproxy.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountProxy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountProxyUpsertBulk) Ignore() *AccountProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountProxyUpsertBulk) DoNothing() *AccountProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountProxyCreateBulk.OnConflict
// documentation for more info.
func (u *AccountProxyUpsertBulk) Update(set func(*AccountProxyUpsert)) *AccountProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountProxyUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountProxyUpsertBulk) SetAccountID(v int64) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountProxyUpsertBulk) UpdateAccountID() *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateAccountID()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *AccountProxyUpsertBulk) SetProxyID(v int64) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *AccountProxyUpsertBulk) UpdateProxyID() *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateProxyID()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *AccountProxyUpsertBulk) SetConcurrency(v int) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *AccountProxyUpsertBulk) AddConcurrency(v int) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *AccountProxyUpsertBulk) UpdateConcurrency() *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateConcurrency()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AccountProxyUpsertBulk) SetSortOrder(v int) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AccountProxyUpsertBulk) AddSortOrder(v int) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AccountProxyUpsertBulk) UpdateSortOrder() *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountProxyUpsertBulk) SetUpdatedAt(v time.Time) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountProxyUpsertBulk) UpdateUpdatedAt() *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountProxyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountProxyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountProxyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountProxyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
