// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/admintelegrambinding"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AdminTelegramBindingDelete is the builder for deleting a AdminTelegramBinding entity.
type AdminTelegramBindingDelete struct {
	config
	hooks    []Hook
	mutation *AdminTelegramBindingMutation
}

// Where appends a list predicates to the AdminTelegramBindingDelete builder.
func (_d *AdminTelegramBindingDelete) Where(ps ...predicate.AdminTelegramBinding) *AdminTelegramBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AdminTelegramBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminTelegramBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AdminTelegramBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(admintelegrambinding.Table, sqlgraph.NewFieldSpec(admintelegrambinding.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AdminTelegramBindingDeleteOne is the builder for deleting a single AdminTelegramBinding entity.
type AdminTelegramBindingDeleteOne struct {
	_d *AdminTelegramBindingDelete
}

// Where appends a list predicates to the AdminTelegramBindingDelete builder.
func (_d *AdminTelegramBindingDeleteOne) Where(ps ...predicate.AdminTelegramBinding) *AdminTelegramBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AdminTelegramBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{admintelegrambinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminTelegramBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
