// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/admintelegrambinding"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AdminTelegramBindingUpdate is the builder for updating AdminTelegramBinding entities.
type AdminTelegramBindingUpdate struct {
	config
	hooks    []Hook
	mutation *AdminTelegramBindingMutation
}

// Where appends a list predicates to the AdminTelegramBindingUpdate builder.
func (_u *AdminTelegramBindingUpdate) Where(ps ...predicate.AdminTelegramBinding) *AdminTelegramBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAdminID sets the "admin_id" field.
func (_u *AdminTelegramBindingUpdate) SetAdminID(v int64) *AdminTelegramBindingUpdate {
	_u.mutation.ResetAdminID()
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdate) SetNillableAdminID(v *int64) *AdminTelegramBindingUpdate {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// AddAdminID adds value to the "admin_id" field.
func (_u *AdminTelegramBindingUpdate) AddAdminID(v int64) *AdminTelegramBindingUpdate {
	_u.mutation.AddAdminID(v)
	return _u
}

// SetTelegramUserID sets the "telegram_user_id" field.
func (_u *AdminTelegramBindingUpdate) SetTelegramUserID(v int64) *AdminTelegramBindingUpdate {
	_u.mutation.ResetTelegramUserID()
	_u.mutation.SetTelegramUserID(v)
	return _u
}

// SetNillableTelegramUserID sets the "telegram_user_id" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdate) SetNillableTelegramUserID(v *int64) *AdminTelegramBindingUpdate {
	if v != nil {
		_u.SetTelegramUserID(*v)
	}
	return _u
}

// AddTelegramUserID adds value to the "telegram_user_id" field.
func (_u *AdminTelegramBindingUpdate) AddTelegramUserID(v int64) *AdminTelegramBindingUpdate {
	_u.mutation.AddTelegramUserID(v)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *AdminTelegramBindingUpdate) SetChatID(v int64) *AdminTelegramBindingUpdate {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdate) SetNillableChatID(v *int64) *AdminTelegramBindingUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *AdminTelegramBindingUpdate) AddChatID(v int64) *AdminTelegramBindingUpdate {
	_u.mutation.AddChatID(v)
	return _u
}

// SetTelegramUsername sets the "telegram_username" field.
func (_u *AdminTelegramBindingUpdate) SetTelegramUsername(v string) *AdminTelegramBindingUpdate {
	_u.mutation.SetTelegramUsername(v)
	return _u
}

// SetNillableTelegramUsername sets the "telegram_username" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdate) SetNillableTelegramUsername(v *string) *AdminTelegramBindingUpdate {
	if v != nil {
		_u.SetTelegramUsername(*v)
	}
	return _u
}

// ClearTelegramUsername clears the value of the "telegram_username" field.
func (_u *AdminTelegramBindingUpdate) ClearTelegramUsername() *AdminTelegramBindingUpdate {
	_u.mutation.ClearTelegramUsername()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AdminTelegramBindingUpdate) SetEnabled(v bool) *AdminTelegramBindingUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdate) SetNillableEnabled(v *bool) *AdminTelegramBindingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNotifyNewTicket sets the "notify_new_ticket" field.
func (_u *AdminTelegramBindingUpdate) SetNotifyNewTicket(v bool) *AdminTelegramBindingUpdate {
	_u.mutation.SetNotifyNewTicket(v)
	return _u
}

// SetNillableNotifyNewTicket sets the "notify_new_ticket" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdate) SetNillableNotifyNewTicket(v *bool) *AdminTelegramBindingUpdate {
	if v != nil {
		_u.SetNotifyNewTicket(*v)
	}
	return _u
}

// SetNotifyUserReply sets the "notify_user_reply" field.
func (_u *AdminTelegramBindingUpdate) SetNotifyUserReply(v bool) *AdminTelegramBindingUpdate {
	_u.mutation.SetNotifyUserReply(v)
	return _u
}

// SetNillableNotifyUserReply sets the "notify_user_reply" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdate) SetNillableNotifyUserReply(v *bool) *AdminTelegramBindingUpdate {
	if v != nil {
		_u.SetNotifyUserReply(*v)
	}
	return _u
}

// SetNotifyHighPriority sets the "notify_high_priority" field.
func (_u *AdminTelegramBindingUpdate) SetNotifyHighPriority(v bool) *AdminTelegramBindingUpdate {
	_u.mutation.SetNotifyHighPriority(v)
	return _u
}

// SetNillableNotifyHighPriority sets the "notify_high_priority" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdate) SetNillableNotifyHighPriority(v *bool) *AdminTelegramBindingUpdate {
	if v != nil {
		_u.SetNotifyHighPriority(*v)
	}
	return _u
}

// SetBoundAt sets the "bound_at" field.
func (_u *AdminTelegramBindingUpdate) SetBoundAt(v time.Time) *AdminTelegramBindingUpdate {
	_u.mutation.SetBoundAt(v)
	return _u
}

// SetNillableBoundAt sets the "bound_at" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdate) SetNillableBoundAt(v *time.Time) *AdminTelegramBindingUpdate {
	if v != nil {
		_u.SetBoundAt(*v)
	}
	return _u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_u *AdminTelegramBindingUpdate) SetLastSuccessAt(v time.Time) *AdminTelegramBindingUpdate {
	_u.mutation.SetLastSuccessAt(v)
	return _u
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdate) SetNillableLastSuccessAt(v *time.Time) *AdminTelegramBindingUpdate {
	if v != nil {
		_u.SetLastSuccessAt(*v)
	}
	return _u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (_u *AdminTelegramBindingUpdate) ClearLastSuccessAt() *AdminTelegramBindingUpdate {
	_u.mutation.ClearLastSuccessAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *AdminTelegramBindingUpdate) SetLastError(v string) *AdminTelegramBindingUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdate) SetNillableLastError(v *string) *AdminTelegramBindingUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *AdminTelegramBindingUpdate) ClearLastError() *AdminTelegramBindingUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminTelegramBindingUpdate) SetUpdatedAt(v time.Time) *AdminTelegramBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdminTelegramBindingMutation object of the builder.
func (_u *AdminTelegramBindingUpdate) Mutation() *AdminTelegramBindingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminTelegramBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminTelegramBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminTelegramBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminTelegramBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminTelegramBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := admintelegrambinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminTelegramBindingUpdate) check() error {
	if v, ok := _u.mutation.TelegramUsername(); ok {
		if err := admintelegrambinding.TelegramUsernameValidator(v); err != nil {
			return &ValidationError{Name: "telegram_username", err: fmt.Errorf(`ent: validator failed for field "AdminTelegramBinding.telegram_username": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminTelegramBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(admintelegrambinding.Table, admintelegrambinding.Columns, sqlgraph.NewFieldSpec(admintelegrambinding.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AdminID(); ok {
		_spec.SetField(admintelegrambinding.FieldAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAdminID(); ok {
		_spec.AddField(admintelegrambinding.FieldAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TelegramUserID(); ok {
		_spec.SetField(admintelegrambinding.FieldTelegramUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegramUserID(); ok {
		_spec.AddField(admintelegrambinding.FieldTelegramUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(admintelegrambinding.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(admintelegrambinding.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TelegramUsername(); ok {
		_spec.SetField(admintelegrambinding.FieldTelegramUsername, field.TypeString, value)
	}
	if _u.mutation.TelegramUsernameCleared() {
		_spec.ClearField(admintelegrambinding.FieldTelegramUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(admintelegrambinding.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyNewTicket(); ok {
		_spec.SetField(admintelegrambinding.FieldNotifyNewTicket, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyUserReply(); ok {
		_spec.SetField(admintelegrambinding.FieldNotifyUserReply, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyHighPriority(); ok {
		_spec.SetField(admintelegrambinding.FieldNotifyHighPriority, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BoundAt(); ok {
		_spec.SetField(admintelegrambinding.FieldBoundAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSuccessAt(); ok {
		_spec.SetField(admintelegrambinding.FieldLastSuccessAt, field.TypeTime, value)
	}
	if _u.mutation.LastSuccessAtCleared() {
		_spec.ClearField(admintelegrambinding.FieldLastSuccessAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(admintelegrambinding.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(admintelegrambinding.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(admintelegrambinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{admintelegrambinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminTelegramBindingUpdateOne is the builder for updating a single AdminTelegramBinding entity.
type AdminTelegramBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminTelegramBindingMutation
}

// SetAdminID sets the "admin_id" field.
func (_u *AdminTelegramBindingUpdateOne) SetAdminID(v int64) *AdminTelegramBindingUpdateOne {
	_u.mutation.ResetAdminID()
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdateOne) SetNillableAdminID(v *int64) *AdminTelegramBindingUpdateOne {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// AddAdminID adds value to the "admin_id" field.
func (_u *AdminTelegramBindingUpdateOne) AddAdminID(v int64) *AdminTelegramBindingUpdateOne {
	_u.mutation.AddAdminID(v)
	return _u
}

// SetTelegramUserID sets the "telegram_user_id" field.
func (_u *AdminTelegramBindingUpdateOne) SetTelegramUserID(v int64) *AdminTelegramBindingUpdateOne {
	_u.mutation.ResetTelegramUserID()
	_u.mutation.SetTelegramUserID(v)
	return _u
}

// SetNillableTelegramUserID sets the "telegram_user_id" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdateOne) SetNillableTelegramUserID(v *int64) *AdminTelegramBindingUpdateOne {
	if v != nil {
		_u.SetTelegramUserID(*v)
	}
	return _u
}

// AddTelegramUserID adds value to the "telegram_user_id" field.
func (_u *AdminTelegramBindingUpdateOne) AddTelegramUserID(v int64) *AdminTelegramBindingUpdateOne {
	_u.mutation.AddTelegramUserID(v)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *AdminTelegramBindingUpdateOne) SetChatID(v int64) *AdminTelegramBindingUpdateOne {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdateOne) SetNillableChatID(v *int64) *AdminTelegramBindingUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *AdminTelegramBindingUpdateOne) AddChatID(v int64) *AdminTelegramBindingUpdateOne {
	_u.mutation.AddChatID(v)
	return _u
}

// SetTelegramUsername sets the "telegram_username" field.
func (_u *AdminTelegramBindingUpdateOne) SetTelegramUsername(v string) *AdminTelegramBindingUpdateOne {
	_u.mutation.SetTelegramUsername(v)
	return _u
}

// SetNillableTelegramUsername sets the "telegram_username" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdateOne) SetNillableTelegramUsername(v *string) *AdminTelegramBindingUpdateOne {
	if v != nil {
		_u.SetTelegramUsername(*v)
	}
	return _u
}

// ClearTelegramUsername clears the value of the "telegram_username" field.
func (_u *AdminTelegramBindingUpdateOne) ClearTelegramUsername() *AdminTelegramBindingUpdateOne {
	_u.mutation.ClearTelegramUsername()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AdminTelegramBindingUpdateOne) SetEnabled(v bool) *AdminTelegramBindingUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdateOne) SetNillableEnabled(v *bool) *AdminTelegramBindingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNotifyNewTicket sets the "notify_new_ticket" field.
func (_u *AdminTelegramBindingUpdateOne) SetNotifyNewTicket(v bool) *AdminTelegramBindingUpdateOne {
	_u.mutation.SetNotifyNewTicket(v)
	return _u
}

// SetNillableNotifyNewTicket sets the "notify_new_ticket" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdateOne) SetNillableNotifyNewTicket(v *bool) *AdminTelegramBindingUpdateOne {
	if v != nil {
		_u.SetNotifyNewTicket(*v)
	}
	return _u
}

// SetNotifyUserReply sets the "notify_user_reply" field.
func (_u *AdminTelegramBindingUpdateOne) SetNotifyUserReply(v bool) *AdminTelegramBindingUpdateOne {
	_u.mutation.SetNotifyUserReply(v)
	return _u
}

// SetNillableNotifyUserReply sets the "notify_user_reply" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdateOne) SetNillableNotifyUserReply(v *bool) *AdminTelegramBindingUpdateOne {
	if v != nil {
		_u.SetNotifyUserReply(*v)
	}
	return _u
}

// SetNotifyHighPriority sets the "notify_high_priority" field.
func (_u *AdminTelegramBindingUpdateOne) SetNotifyHighPriority(v bool) *AdminTelegramBindingUpdateOne {
	_u.mutation.SetNotifyHighPriority(v)
	return _u
}

// SetNillableNotifyHighPriority sets the "notify_high_priority" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdateOne) SetNillableNotifyHighPriority(v *bool) *AdminTelegramBindingUpdateOne {
	if v != nil {
		_u.SetNotifyHighPriority(*v)
	}
	return _u
}

// SetBoundAt sets the "bound_at" field.
func (_u *AdminTelegramBindingUpdateOne) SetBoundAt(v time.Time) *AdminTelegramBindingUpdateOne {
	_u.mutation.SetBoundAt(v)
	return _u
}

// SetNillableBoundAt sets the "bound_at" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdateOne) SetNillableBoundAt(v *time.Time) *AdminTelegramBindingUpdateOne {
	if v != nil {
		_u.SetBoundAt(*v)
	}
	return _u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_u *AdminTelegramBindingUpdateOne) SetLastSuccessAt(v time.Time) *AdminTelegramBindingUpdateOne {
	_u.mutation.SetLastSuccessAt(v)
	return _u
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdateOne) SetNillableLastSuccessAt(v *time.Time) *AdminTelegramBindingUpdateOne {
	if v != nil {
		_u.SetLastSuccessAt(*v)
	}
	return _u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (_u *AdminTelegramBindingUpdateOne) ClearLastSuccessAt() *AdminTelegramBindingUpdateOne {
	_u.mutation.ClearLastSuccessAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *AdminTelegramBindingUpdateOne) SetLastError(v string) *AdminTelegramBindingUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *AdminTelegramBindingUpdateOne) SetNillableLastError(v *string) *AdminTelegramBindingUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *AdminTelegramBindingUpdateOne) ClearLastError() *AdminTelegramBindingUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminTelegramBindingUpdateOne) SetUpdatedAt(v time.Time) *AdminTelegramBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdminTelegramBindingMutation object of the builder.
func (_u *AdminTelegramBindingUpdateOne) Mutation() *AdminTelegramBindingMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminTelegramBindingUpdate builder.
func (_u *AdminTelegramBindingUpdateOne) Where(ps ...predicate.AdminTelegramBinding) *AdminTelegramBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminTelegramBindingUpdateOne) Select(field string, fields ...string) *AdminTelegramBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminTelegramBinding entity.
func (_u *AdminTelegramBindingUpdateOne) Save(ctx context.Context) (*AdminTelegramBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminTelegramBindingUpdateOne) SaveX(ctx context.Context) *AdminTelegramBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminTelegramBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminTelegramBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminTelegramBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := admintelegrambinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminTelegramBindingUpdateOne) check() error {
	if v, ok := _u.mutation.TelegramUsername(); ok {
		if err := admintelegrambinding.TelegramUsernameValidator(v); err != nil {
			return &ValidationError{Name: "telegram_username", err: fmt.Errorf(`ent: validator failed for field "AdminTelegramBinding.telegram_username": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminTelegramBindingUpdateOne) sqlSave(ctx context.Context) (_node *AdminTelegramBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(admintelegrambinding.Table, admintelegrambinding.Columns, sqlgraph.NewFieldSpec(admintelegrambinding.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminTelegramBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, admintelegrambinding.FieldID)
		for _, f := range fields {
			if !admintelegrambinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != admintelegrambinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AdminID(); ok {
		_spec.SetField(admintelegrambinding.FieldAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAdminID(); ok {
		_spec.AddField(admintelegrambinding.FieldAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TelegramUserID(); ok {
		_spec.SetField(admintelegrambinding.FieldTelegramUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegramUserID(); ok {
		_spec.AddField(admintelegrambinding.FieldTelegramUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(admintelegrambinding.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(admintelegrambinding.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TelegramUsername(); ok {
		_spec.SetField(admintelegrambinding.FieldTelegramUsername, field.TypeString, value)
	}
	if _u.mutation.TelegramUsernameCleared() {
		_spec.ClearField(admintelegrambinding.FieldTelegramUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(admintelegrambinding.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyNewTicket(); ok {
		_spec.SetField(admintelegrambinding.FieldNotifyNewTicket, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyUserReply(); ok {
		_spec.SetField(admintelegrambinding.FieldNotifyUserReply, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyHighPriority(); ok {
		_spec.SetField(admintelegrambinding.FieldNotifyHighPriority, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BoundAt(); ok {
		_spec.SetField(admintelegrambinding.FieldBoundAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSuccessAt(); ok {
		_spec.SetField(admintelegrambinding.FieldLastSuccessAt, field.TypeTime, value)
	}
	if _u.mutation.LastSuccessAtCleared() {
		_spec.ClearField(admintelegrambinding.FieldLastSuccessAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(admintelegrambinding.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(admintelegrambinding.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(admintelegrambinding.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AdminTelegramBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{admintelegrambinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
