// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/routingartifactversion"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RoutingArtifactVersionQuery is the builder for querying RoutingArtifactVersion entities.
type RoutingArtifactVersionQuery struct {
	config
	ctx         *QueryContext
	order       []routingartifactversion.OrderOption
	inters      []Interceptor
	predicates  []predicate.RoutingArtifactVersion
	withCreator *UserQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoutingArtifactVersionQuery builder.
func (_q *RoutingArtifactVersionQuery) Where(ps ...predicate.RoutingArtifactVersion) *RoutingArtifactVersionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RoutingArtifactVersionQuery) Limit(limit int) *RoutingArtifactVersionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RoutingArtifactVersionQuery) Offset(offset int) *RoutingArtifactVersionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RoutingArtifactVersionQuery) Unique(unique bool) *RoutingArtifactVersionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RoutingArtifactVersionQuery) Order(o ...routingartifactversion.OrderOption) *RoutingArtifactVersionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCreator chains the current query on the "creator" edge.
func (_q *RoutingArtifactVersionQuery) QueryCreator() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(routingartifactversion.Table, routingartifactversion.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, routingartifactversion.CreatorTable, routingartifactversion.CreatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RoutingArtifactVersion entity from the query.
// Returns a *NotFoundError when no RoutingArtifactVersion was found.
func (_q *RoutingArtifactVersionQuery) First(ctx context.Context) (*RoutingArtifactVersion, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{routingartifactversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RoutingArtifactVersionQuery) FirstX(ctx context.Context) *RoutingArtifactVersion {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoutingArtifactVersion ID from the query.
// Returns a *NotFoundError when no RoutingArtifactVersion ID was found.
func (_q *RoutingArtifactVersionQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{routingartifactversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RoutingArtifactVersionQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoutingArtifactVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RoutingArtifactVersion entity is found.
// Returns a *NotFoundError when no RoutingArtifactVersion entities are found.
func (_q *RoutingArtifactVersionQuery) Only(ctx context.Context) (*RoutingArtifactVersion, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{routingartifactversion.Label}
	default:
		return nil, &NotSingularError{routingartifactversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RoutingArtifactVersionQuery) OnlyX(ctx context.Context) *RoutingArtifactVersion {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoutingArtifactVersion ID in the query.
// Returns a *NotSingularError when more than one RoutingArtifactVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RoutingArtifactVersionQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{routingartifactversion.Label}
	default:
		err = &NotSingularError{routingartifactversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RoutingArtifactVersionQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoutingArtifactVersions.
func (_q *RoutingArtifactVersionQuery) All(ctx context.Context) ([]*RoutingArtifactVersion, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RoutingArtifactVersion, *RoutingArtifactVersionQuery]()
	return withInterceptors[[]*RoutingArtifactVersion](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RoutingArtifactVersionQuery) AllX(ctx context.Context) []*RoutingArtifactVersion {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoutingArtifactVersion IDs.
func (_q *RoutingArtifactVersionQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(routingartifactversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RoutingArtifactVersionQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RoutingArtifactVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RoutingArtifactVersionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RoutingArtifactVersionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RoutingArtifactVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RoutingArtifactVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoutingArtifactVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RoutingArtifactVersionQuery) Clone() *RoutingArtifactVersionQuery {
	if _q == nil {
		return nil
	}
	return &RoutingArtifactVersionQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]routingartifactversion.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.RoutingArtifactVersion{}, _q.predicates...),
		withCreator: _q.withCreator.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCreator tells the query-builder to eager-load the nodes that are connected to
// the "creator" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RoutingArtifactVersionQuery) WithCreator(opts ...func(*UserQuery)) *RoutingArtifactVersionQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCreator = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ArtifactKind string `json:"artifact_kind,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoutingArtifactVersion.Query().
//		GroupBy(routingartifactversion.FieldArtifactKind).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RoutingArtifactVersionQuery) GroupBy(field string, fields ...string) *RoutingArtifactVersionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RoutingArtifactVersionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = routingartifactversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ArtifactKind string `json:"artifact_kind,omitempty"`
//	}
//
//	client.RoutingArtifactVersion.Query().
//		Select(routingartifactversion.FieldArtifactKind).
//		Scan(ctx, &v)
func (_q *RoutingArtifactVersionQuery) Select(fields ...string) *RoutingArtifactVersionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RoutingArtifactVersionSelect{RoutingArtifactVersionQuery: _q}
	sbuild.label = routingartifactversion.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RoutingArtifactVersionSelect configured with the given aggregations.
func (_q *RoutingArtifactVersionQuery) Aggregate(fns ...AggregateFunc) *RoutingArtifactVersionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RoutingArtifactVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !routingartifactversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RoutingArtifactVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RoutingArtifactVersion, error) {
	var (
		nodes       = []*RoutingArtifactVersion{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withCreator != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RoutingArtifactVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RoutingArtifactVersion{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCreator; query != nil {
		if err := _q.loadCreator(ctx, query, nodes, nil,
			func(n *RoutingArtifactVersion, e *User) { n.Edges.Creator = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RoutingArtifactVersionQuery) loadCreator(ctx context.Context, query *UserQuery, nodes []*RoutingArtifactVersion, init func(*RoutingArtifactVersion), assign func(*RoutingArtifactVersion, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*RoutingArtifactVersion)
	for i := range nodes {
		if nodes[i].CreatedBy == nil {
			continue
		}
		fk := *nodes[i].CreatedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "created_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *RoutingArtifactVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RoutingArtifactVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(routingartifactversion.Table, routingartifactversion.Columns, sqlgraph.NewFieldSpec(routingartifactversion.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, routingartifactversion.FieldID)
		for i := range fields {
			if fields[i] != routingartifactversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCreator != nil {
			_spec.Node.AddColumnOnce(routingartifactversion.FieldCreatedBy)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RoutingArtifactVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(routingartifactversion.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = routingartifactversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *RoutingArtifactVersionQuery) ForUpdate(opts ...sql.LockOption) *RoutingArtifactVersionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *RoutingArtifactVersionQuery) ForShare(opts ...sql.LockOption) *RoutingArtifactVersionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// RoutingArtifactVersionGroupBy is the group-by builder for RoutingArtifactVersion entities.
type RoutingArtifactVersionGroupBy struct {
	selector
	build *RoutingArtifactVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RoutingArtifactVersionGroupBy) Aggregate(fns ...AggregateFunc) *RoutingArtifactVersionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RoutingArtifactVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoutingArtifactVersionQuery, *RoutingArtifactVersionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RoutingArtifactVersionGroupBy) sqlScan(ctx context.Context, root *RoutingArtifactVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RoutingArtifactVersionSelect is the builder for selecting fields of RoutingArtifactVersion entities.
type RoutingArtifactVersionSelect struct {
	*RoutingArtifactVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RoutingArtifactVersionSelect) Aggregate(fns ...AggregateFunc) *RoutingArtifactVersionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RoutingArtifactVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoutingArtifactVersionQuery, *RoutingArtifactVersionSelect](ctx, _s.RoutingArtifactVersionQuery, _s, _s.inters, v)
}

func (_s *RoutingArtifactVersionSelect) sqlScan(ctx context.Context, root *RoutingArtifactVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
