// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/routingartifactversion"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RoutingArtifactVersionCreate is the builder for creating a RoutingArtifactVersion entity.
type RoutingArtifactVersionCreate struct {
	config
	mutation *RoutingArtifactVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetArtifactKind sets the "artifact_kind" field.
func (_c *RoutingArtifactVersionCreate) SetArtifactKind(v string) *RoutingArtifactVersionCreate {
	_c.mutation.SetArtifactKind(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *RoutingArtifactVersionCreate) SetVersion(v string) *RoutingArtifactVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetParentVersion sets the "parent_version" field.
func (_c *RoutingArtifactVersionCreate) SetParentVersion(v string) *RoutingArtifactVersionCreate {
	_c.mutation.SetParentVersion(v)
	return _c
}

// SetNillableParentVersion sets the "parent_version" field if the given value is not nil.
func (_c *RoutingArtifactVersionCreate) SetNillableParentVersion(v *string) *RoutingArtifactVersionCreate {
	if v != nil {
		_c.SetParentVersion(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *RoutingArtifactVersionCreate) SetPlatform(v string) *RoutingArtifactVersionCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetModelFamily sets the "model_family" field.
func (_c *RoutingArtifactVersionCreate) SetModelFamily(v string) *RoutingArtifactVersionCreate {
	_c.mutation.SetModelFamily(v)
	return _c
}

// SetEndpointKind sets the "endpoint_kind" field.
func (_c *RoutingArtifactVersionCreate) SetEndpointKind(v string) *RoutingArtifactVersionCreate {
	_c.mutation.SetEndpointKind(v)
	return _c
}

// SetPreference sets the "preference" field.
func (_c *RoutingArtifactVersionCreate) SetPreference(v string) *RoutingArtifactVersionCreate {
	_c.mutation.SetPreference(v)
	return _c
}

// SetNillablePreference sets the "preference" field if the given value is not nil.
func (_c *RoutingArtifactVersionCreate) SetNillablePreference(v *string) *RoutingArtifactVersionCreate {
	if v != nil {
		_c.SetPreference(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RoutingArtifactVersionCreate) SetStatus(v string) *RoutingArtifactVersionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RoutingArtifactVersionCreate) SetNillableStatus(v *string) *RoutingArtifactVersionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSchemaVersion sets the "schema_version" field.
func (_c *RoutingArtifactVersionCreate) SetSchemaVersion(v string) *RoutingArtifactVersionCreate {
	_c.mutation.SetSchemaVersion(v)
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *RoutingArtifactVersionCreate) SetChecksum(v string) *RoutingArtifactVersionCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *RoutingArtifactVersionCreate) SetPayload(v jsontext.Value) *RoutingArtifactVersionCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetDependencies sets the "dependencies" field.
func (_c *RoutingArtifactVersionCreate) SetDependencies(v jsontext.Value) *RoutingArtifactVersionCreate {
	_c.mutation.SetDependencies(v)
	return _c
}

// SetLineage sets the "lineage" field.
func (_c *RoutingArtifactVersionCreate) SetLineage(v jsontext.Value) *RoutingArtifactVersionCreate {
	_c.mutation.SetLineage(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *RoutingArtifactVersionCreate) SetCreatedBy(v int64) *RoutingArtifactVersionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *RoutingArtifactVersionCreate) SetNillableCreatedBy(v *int64) *RoutingArtifactVersionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetActivatedAt sets the "activated_at" field.
func (_c *RoutingArtifactVersionCreate) SetActivatedAt(v time.Time) *RoutingArtifactVersionCreate {
	_c.mutation.SetActivatedAt(v)
	return _c
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_c *RoutingArtifactVersionCreate) SetNillableActivatedAt(v *time.Time) *RoutingArtifactVersionCreate {
	if v != nil {
		_c.SetActivatedAt(*v)
	}
	return _c
}

// SetRetiredAt sets the "retired_at" field.
func (_c *RoutingArtifactVersionCreate) SetRetiredAt(v time.Time) *RoutingArtifactVersionCreate {
	_c.mutation.SetRetiredAt(v)
	return _c
}

// SetNillableRetiredAt sets the "retired_at" field if the given value is not nil.
func (_c *RoutingArtifactVersionCreate) SetNillableRetiredAt(v *time.Time) *RoutingArtifactVersionCreate {
	if v != nil {
		_c.SetRetiredAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RoutingArtifactVersionCreate) SetCreatedAt(v time.Time) *RoutingArtifactVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RoutingArtifactVersionCreate) SetNillableCreatedAt(v *time.Time) *RoutingArtifactVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *RoutingArtifactVersionCreate) SetCreatorID(id int64) *RoutingArtifactVersionCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_c *RoutingArtifactVersionCreate) SetNillableCreatorID(id *int64) *RoutingArtifactVersionCreate {
	if id != nil {
		_c = _c.SetCreatorID(*id)
	}
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *RoutingArtifactVersionCreate) SetCreator(v *User) *RoutingArtifactVersionCreate {
	return _c.SetCreatorID(v.ID)
}

// Mutation returns the RoutingArtifactVersionMutation object of the builder.
func (_c *RoutingArtifactVersionCreate) Mutation() *RoutingArtifactVersionMutation {
	return _c.mutation
}

// Save creates the RoutingArtifactVersion in the database.
func (_c *RoutingArtifactVersionCreate) Save(ctx context.Context) (*RoutingArtifactVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoutingArtifactVersionCreate) SaveX(ctx context.Context) *RoutingArtifactVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoutingArtifactVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoutingArtifactVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RoutingArtifactVersionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := routingartifactversion.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := routingartifactversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoutingArtifactVersionCreate) check() error {
	if _, ok := _c.mutation.ArtifactKind(); !ok {
		return &ValidationError{Name: "artifact_kind", err: errors.New(`ent: missing required field "RoutingArtifactVersion.artifact_kind"`)}
	}
	if v, ok := _c.mutation.ArtifactKind(); ok {
		if err := routingartifactversion.ArtifactKindValidator(v); err != nil {
			return &ValidationError{Name: "artifact_kind", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.artifact_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "RoutingArtifactVersion.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := routingartifactversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.version": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ParentVersion(); ok {
		if err := routingartifactversion.ParentVersionValidator(v); err != nil {
			return &ValidationError{Name: "parent_version", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.parent_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "RoutingArtifactVersion.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := routingartifactversion.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelFamily(); !ok {
		return &ValidationError{Name: "model_family", err: errors.New(`ent: missing required field "RoutingArtifactVersion.model_family"`)}
	}
	if v, ok := _c.mutation.ModelFamily(); ok {
		if err := routingartifactversion.ModelFamilyValidator(v); err != nil {
			return &ValidationError{Name: "model_family", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.model_family": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EndpointKind(); !ok {
		return &ValidationError{Name: "endpoint_kind", err: errors.New(`ent: missing required field "RoutingArtifactVersion.endpoint_kind"`)}
	}
	if v, ok := _c.mutation.EndpointKind(); ok {
		if err := routingartifactversion.EndpointKindValidator(v); err != nil {
			return &ValidationError{Name: "endpoint_kind", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.endpoint_kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Preference(); ok {
		if err := routingartifactversion.PreferenceValidator(v); err != nil {
			return &ValidationError{Name: "preference", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.preference": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RoutingArtifactVersion.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := routingartifactversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		return &ValidationError{Name: "schema_version", err: errors.New(`ent: missing required field "RoutingArtifactVersion.schema_version"`)}
	}
	if v, ok := _c.mutation.SchemaVersion(); ok {
		if err := routingartifactversion.SchemaVersionValidator(v); err != nil {
			return &ValidationError{Name: "schema_version", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.schema_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Checksum(); !ok {
		return &ValidationError{Name: "checksum", err: errors.New(`ent: missing required field "RoutingArtifactVersion.checksum"`)}
	}
	if v, ok := _c.mutation.Checksum(); ok {
		if err := routingartifactversion.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.checksum": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RoutingArtifactVersion.created_at"`)}
	}
	return nil
}

func (_c *RoutingArtifactVersionCreate) sqlSave(ctx context.Context) (*RoutingArtifactVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoutingArtifactVersionCreate) createSpec() (*RoutingArtifactVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &RoutingArtifactVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(routingartifactversion.Table, sqlgraph.NewFieldSpec(routingartifactversion.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ArtifactKind(); ok {
		_spec.SetField(routingartifactversion.FieldArtifactKind, field.TypeString, value)
		_node.ArtifactKind = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(routingartifactversion.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.ParentVersion(); ok {
		_spec.SetField(routingartifactversion.FieldParentVersion, field.TypeString, value)
		_node.ParentVersion = &value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(routingartifactversion.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.ModelFamily(); ok {
		_spec.SetField(routingartifactversion.FieldModelFamily, field.TypeString, value)
		_node.ModelFamily = value
	}
	if value, ok := _c.mutation.EndpointKind(); ok {
		_spec.SetField(routingartifactversion.FieldEndpointKind, field.TypeString, value)
		_node.EndpointKind = value
	}
	if value, ok := _c.mutation.Preference(); ok {
		_spec.SetField(routingartifactversion.FieldPreference, field.TypeString, value)
		_node.Preference = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(routingartifactversion.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SchemaVersion(); ok {
		_spec.SetField(routingartifactversion.FieldSchemaVersion, field.TypeString, value)
		_node.SchemaVersion = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(routingartifactversion.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(routingartifactversion.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Dependencies(); ok {
		_spec.SetField(routingartifactversion.FieldDependencies, field.TypeJSON, value)
		_node.Dependencies = value
	}
	if value, ok := _c.mutation.Lineage(); ok {
		_spec.SetField(routingartifactversion.FieldLineage, field.TypeJSON, value)
		_node.Lineage = value
	}
	if value, ok := _c.mutation.ActivatedAt(); ok {
		_spec.SetField(routingartifactversion.FieldActivatedAt, field.TypeTime, value)
		_node.ActivatedAt = &value
	}
	if value, ok := _c.mutation.RetiredAt(); ok {
		_spec.SetField(routingartifactversion.FieldRetiredAt, field.TypeTime, value)
		_node.RetiredAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(routingartifactversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   routingartifactversion.CreatorTable,
			Columns: []string{routingartifactversion.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RoutingArtifactVersion.Create().
//		SetArtifactKind(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RoutingArtifactVersionUpsert) {
//			SetArtifactKind(v+v).
//		}).
//		Exec(ctx)
func (_c *RoutingArtifactVersionCreate) OnConflict(opts ...sql.ConflictOption) *RoutingArtifactVersionUpsertOne {
	_c.conflict = opts
	return &RoutingArtifactVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RoutingArtifactVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RoutingArtifactVersionCreate) OnConflictColumns(columns ...string) *RoutingArtifactVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RoutingArtifactVersionUpsertOne{
		create: _c,
	}
}

type (
	// RoutingArtifactVersionUpsertOne is the builder for "upsert"-ing
	//  one RoutingArtifactVersion node.
	RoutingArtifactVersionUpsertOne struct {
		create *RoutingArtifactVersionCreate
	}

	// RoutingArtifactVersionUpsert is the "OnConflict" setter.
	RoutingArtifactVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetArtifactKind sets the "artifact_kind" field.
func (u *RoutingArtifactVersionUpsert) SetArtifactKind(v string) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldArtifactKind, v)
	return u
}

// UpdateArtifactKind sets the "artifact_kind" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateArtifactKind() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldArtifactKind)
	return u
}

// SetVersion sets the "version" field.
func (u *RoutingArtifactVersionUpsert) SetVersion(v string) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateVersion() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldVersion)
	return u
}

// SetParentVersion sets the "parent_version" field.
func (u *RoutingArtifactVersionUpsert) SetParentVersion(v string) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldParentVersion, v)
	return u
}

// UpdateParentVersion sets the "parent_version" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateParentVersion() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldParentVersion)
	return u
}

// ClearParentVersion clears the value of the "parent_version" field.
func (u *RoutingArtifactVersionUpsert) ClearParentVersion() *RoutingArtifactVersionUpsert {
	u.SetNull(routingartifactversion.FieldParentVersion)
	return u
}

// SetPlatform sets the "platform" field.
func (u *RoutingArtifactVersionUpsert) SetPlatform(v string) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdatePlatform() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldPlatform)
	return u
}

// SetModelFamily sets the "model_family" field.
func (u *RoutingArtifactVersionUpsert) SetModelFamily(v string) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldModelFamily, v)
	return u
}

// UpdateModelFamily sets the "model_family" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateModelFamily() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldModelFamily)
	return u
}

// SetEndpointKind sets the "endpoint_kind" field.
func (u *RoutingArtifactVersionUpsert) SetEndpointKind(v string) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldEndpointKind, v)
	return u
}

// UpdateEndpointKind sets the "endpoint_kind" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateEndpointKind() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldEndpointKind)
	return u
}

// SetPreference sets the "preference" field.
func (u *RoutingArtifactVersionUpsert) SetPreference(v string) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldPreference, v)
	return u
}

// UpdatePreference sets the "preference" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdatePreference() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldPreference)
	return u
}

// ClearPreference clears the value of the "preference" field.
func (u *RoutingArtifactVersionUpsert) ClearPreference() *RoutingArtifactVersionUpsert {
	u.SetNull(routingartifactversion.FieldPreference)
	return u
}

// SetStatus sets the "status" field.
func (u *RoutingArtifactVersionUpsert) SetStatus(v string) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateStatus() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldStatus)
	return u
}

// SetSchemaVersion sets the "schema_version" field.
func (u *RoutingArtifactVersionUpsert) SetSchemaVersion(v string) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldSchemaVersion, v)
	return u
}

// UpdateSchemaVersion sets the "schema_version" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateSchemaVersion() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldSchemaVersion)
	return u
}

// SetChecksum sets the "checksum" field.
func (u *RoutingArtifactVersionUpsert) SetChecksum(v string) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldChecksum, v)
	return u
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateChecksum() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldChecksum)
	return u
}

// SetPayload sets the "payload" field.
func (u *RoutingArtifactVersionUpsert) SetPayload(v jsontext.Value) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdatePayload() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldPayload)
	return u
}

// ClearPayload clears the value of the "payload" field.
func (u *RoutingArtifactVersionUpsert) ClearPayload() *RoutingArtifactVersionUpsert {
	u.SetNull(routingartifactversion.FieldPayload)
	return u
}

// SetDependencies sets the "dependencies" field.
func (u *RoutingArtifactVersionUpsert) SetDependencies(v jsontext.Value) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldDependencies, v)
	return u
}

// UpdateDependencies sets the "dependencies" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateDependencies() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldDependencies)
	return u
}

// ClearDependencies clears the value of the "dependencies" field.
func (u *RoutingArtifactVersionUpsert) ClearDependencies() *RoutingArtifactVersionUpsert {
	u.SetNull(routingartifactversion.FieldDependencies)
	return u
}

// SetLineage sets the "lineage" field.
func (u *RoutingArtifactVersionUpsert) SetLineage(v jsontext.Value) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldLineage, v)
	return u
}

// UpdateLineage sets the "lineage" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateLineage() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldLineage)
	return u
}

// ClearLineage clears the value of the "lineage" field.
func (u *RoutingArtifactVersionUpsert) ClearLineage() *RoutingArtifactVersionUpsert {
	u.SetNull(routingartifactversion.FieldLineage)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *RoutingArtifactVersionUpsert) SetCreatedBy(v int64) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateCreatedBy() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *RoutingArtifactVersionUpsert) ClearCreatedBy() *RoutingArtifactVersionUpsert {
	u.SetNull(routingartifactversion.FieldCreatedBy)
	return u
}

// SetActivatedAt sets the "activated_at" field.
func (u *RoutingArtifactVersionUpsert) SetActivatedAt(v time.Time) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldActivatedAt, v)
	return u
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateActivatedAt() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldActivatedAt)
	return u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (u *RoutingArtifactVersionUpsert) ClearActivatedAt() *RoutingArtifactVersionUpsert {
	u.SetNull(routingartifactversion.FieldActivatedAt)
	return u
}

// SetRetiredAt sets the "retired_at" field.
func (u *RoutingArtifactVersionUpsert) SetRetiredAt(v time.Time) *RoutingArtifactVersionUpsert {
	u.Set(routingartifactversion.FieldRetiredAt, v)
	return u
}

// UpdateRetiredAt sets the "retired_at" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsert) UpdateRetiredAt() *RoutingArtifactVersionUpsert {
	u.SetExcluded(routingartifactversion.FieldRetiredAt)
	return u
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (u *RoutingArtifactVersionUpsert) ClearRetiredAt() *RoutingArtifactVersionUpsert {
	u.SetNull(routingartifactversion.FieldRetiredAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RoutingArtifactVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RoutingArtifactVersionUpsertOne) UpdateNewValues() *RoutingArtifactVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(routingartifactversion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RoutingArtifactVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RoutingArtifactVersionUpsertOne) Ignore() *RoutingArtifactVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RoutingArtifactVersionUpsertOne) DoNothing() *RoutingArtifactVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RoutingArtifactVersionCreate.OnConflict
// documentation for more info.
func (u *RoutingArtifactVersionUpsertOne) Update(set func(*RoutingArtifactVersionUpsert)) *RoutingArtifactVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RoutingArtifactVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetArtifactKind sets the "artifact_kind" field.
func (u *RoutingArtifactVersionUpsertOne) SetArtifactKind(v string) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetArtifactKind(v)
	})
}

// UpdateArtifactKind sets the "artifact_kind" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateArtifactKind() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateArtifactKind()
	})
}

// SetVersion sets the "version" field.
func (u *RoutingArtifactVersionUpsertOne) SetVersion(v string) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateVersion() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetParentVersion sets the "parent_version" field.
func (u *RoutingArtifactVersionUpsertOne) SetParentVersion(v string) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetParentVersion(v)
	})
}

// UpdateParentVersion sets the "parent_version" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateParentVersion() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateParentVersion()
	})
}

// ClearParentVersion clears the value of the "parent_version" field.
func (u *RoutingArtifactVersionUpsertOne) ClearParentVersion() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearParentVersion()
	})
}

// SetPlatform sets the "platform" field.
func (u *RoutingArtifactVersionUpsertOne) SetPlatform(v string) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdatePlatform() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdatePlatform()
	})
}

// SetModelFamily sets the "model_family" field.
func (u *RoutingArtifactVersionUpsertOne) SetModelFamily(v string) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetModelFamily(v)
	})
}

// UpdateModelFamily sets the "model_family" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateModelFamily() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateModelFamily()
	})
}

// SetEndpointKind sets the "endpoint_kind" field.
func (u *RoutingArtifactVersionUpsertOne) SetEndpointKind(v string) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetEndpointKind(v)
	})
}

// UpdateEndpointKind sets the "endpoint_kind" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateEndpointKind() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateEndpointKind()
	})
}

// SetPreference sets the "preference" field.
func (u *RoutingArtifactVersionUpsertOne) SetPreference(v string) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetPreference(v)
	})
}

// UpdatePreference sets the "preference" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdatePreference() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdatePreference()
	})
}

// ClearPreference clears the value of the "preference" field.
func (u *RoutingArtifactVersionUpsertOne) ClearPreference() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearPreference()
	})
}

// SetStatus sets the "status" field.
func (u *RoutingArtifactVersionUpsertOne) SetStatus(v string) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateStatus() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetSchemaVersion sets the "schema_version" field.
func (u *RoutingArtifactVersionUpsertOne) SetSchemaVersion(v string) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetSchemaVersion(v)
	})
}

// UpdateSchemaVersion sets the "schema_version" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateSchemaVersion() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateSchemaVersion()
	})
}

// SetChecksum sets the "checksum" field.
func (u *RoutingArtifactVersionUpsertOne) SetChecksum(v string) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateChecksum() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateChecksum()
	})
}

// SetPayload sets the "payload" field.
func (u *RoutingArtifactVersionUpsertOne) SetPayload(v jsontext.Value) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdatePayload() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *RoutingArtifactVersionUpsertOne) ClearPayload() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearPayload()
	})
}

// SetDependencies sets the "dependencies" field.
func (u *RoutingArtifactVersionUpsertOne) SetDependencies(v jsontext.Value) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetDependencies(v)
	})
}

// UpdateDependencies sets the "dependencies" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateDependencies() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateDependencies()
	})
}

// ClearDependencies clears the value of the "dependencies" field.
func (u *RoutingArtifactVersionUpsertOne) ClearDependencies() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearDependencies()
	})
}

// SetLineage sets the "lineage" field.
func (u *RoutingArtifactVersionUpsertOne) SetLineage(v jsontext.Value) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetLineage(v)
	})
}

// UpdateLineage sets the "lineage" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateLineage() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateLineage()
	})
}

// ClearLineage clears the value of the "lineage" field.
func (u *RoutingArtifactVersionUpsertOne) ClearLineage() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearLineage()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *RoutingArtifactVersionUpsertOne) SetCreatedBy(v int64) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateCreatedBy() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *RoutingArtifactVersionUpsertOne) ClearCreatedBy() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearCreatedBy()
	})
}

// SetActivatedAt sets the "activated_at" field.
func (u *RoutingArtifactVersionUpsertOne) SetActivatedAt(v time.Time) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetActivatedAt(v)
	})
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateActivatedAt() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateActivatedAt()
	})
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (u *RoutingArtifactVersionUpsertOne) ClearActivatedAt() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearActivatedAt()
	})
}

// SetRetiredAt sets the "retired_at" field.
func (u *RoutingArtifactVersionUpsertOne) SetRetiredAt(v time.Time) *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetRetiredAt(v)
	})
}

// UpdateRetiredAt sets the "retired_at" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertOne) UpdateRetiredAt() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateRetiredAt()
	})
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (u *RoutingArtifactVersionUpsertOne) ClearRetiredAt() *RoutingArtifactVersionUpsertOne {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearRetiredAt()
	})
}

// Exec executes the query.
func (u *RoutingArtifactVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RoutingArtifactVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RoutingArtifactVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RoutingArtifactVersionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RoutingArtifactVersionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RoutingArtifactVersionCreateBulk is the builder for creating many RoutingArtifactVersion entities in bulk.
type RoutingArtifactVersionCreateBulk struct {
	config
	err      error
	builders []*RoutingArtifactVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the RoutingArtifactVersion entities in the database.
func (_c *RoutingArtifactVersionCreateBulk) Save(ctx context.Context) ([]*RoutingArtifactVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RoutingArtifactVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoutingArtifactVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoutingArtifactVersionCreateBulk) SaveX(ctx context.Context) []*RoutingArtifactVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoutingArtifactVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoutingArtifactVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RoutingArtifactVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RoutingArtifactVersionUpsert) {
//			SetArtifactKind(v+v).
//		}).
//		Exec(ctx)
func (_c *RoutingArtifactVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *RoutingArtifactVersionUpsertBulk {
	_c.conflict = opts
	return &RoutingArtifactVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RoutingArtifactVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RoutingArtifactVersionCreateBulk) OnConflictColumns(columns ...string) *RoutingArtifactVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RoutingArtifactVersionUpsertBulk{
		create: _c,
	}
}

// RoutingArtifactVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of RoutingArtifactVersion nodes.
type RoutingArtifactVersionUpsertBulk struct {
	create *RoutingArtifactVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RoutingArtifactVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RoutingArtifactVersionUpsertBulk) UpdateNewValues() *RoutingArtifactVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(routingartifactversion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RoutingArtifactVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RoutingArtifactVersionUpsertBulk) Ignore() *RoutingArtifactVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RoutingArtifactVersionUpsertBulk) DoNothing() *RoutingArtifactVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RoutingArtifactVersionCreateBulk.OnConflict
// documentation for more info.
func (u *RoutingArtifactVersionUpsertBulk) Update(set func(*RoutingArtifactVersionUpsert)) *RoutingArtifactVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RoutingArtifactVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetArtifactKind sets the "artifact_kind" field.
func (u *RoutingArtifactVersionUpsertBulk) SetArtifactKind(v string) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetArtifactKind(v)
	})
}

// UpdateArtifactKind sets the "artifact_kind" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateArtifactKind() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateArtifactKind()
	})
}

// SetVersion sets the "version" field.
func (u *RoutingArtifactVersionUpsertBulk) SetVersion(v string) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateVersion() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetParentVersion sets the "parent_version" field.
func (u *RoutingArtifactVersionUpsertBulk) SetParentVersion(v string) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetParentVersion(v)
	})
}

// UpdateParentVersion sets the "parent_version" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateParentVersion() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateParentVersion()
	})
}

// ClearParentVersion clears the value of the "parent_version" field.
func (u *RoutingArtifactVersionUpsertBulk) ClearParentVersion() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearParentVersion()
	})
}

// SetPlatform sets the "platform" field.
func (u *RoutingArtifactVersionUpsertBulk) SetPlatform(v string) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdatePlatform() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdatePlatform()
	})
}

// SetModelFamily sets the "model_family" field.
func (u *RoutingArtifactVersionUpsertBulk) SetModelFamily(v string) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetModelFamily(v)
	})
}

// UpdateModelFamily sets the "model_family" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateModelFamily() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateModelFamily()
	})
}

// SetEndpointKind sets the "endpoint_kind" field.
func (u *RoutingArtifactVersionUpsertBulk) SetEndpointKind(v string) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetEndpointKind(v)
	})
}

// UpdateEndpointKind sets the "endpoint_kind" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateEndpointKind() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateEndpointKind()
	})
}

// SetPreference sets the "preference" field.
func (u *RoutingArtifactVersionUpsertBulk) SetPreference(v string) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetPreference(v)
	})
}

// UpdatePreference sets the "preference" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdatePreference() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdatePreference()
	})
}

// ClearPreference clears the value of the "preference" field.
func (u *RoutingArtifactVersionUpsertBulk) ClearPreference() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearPreference()
	})
}

// SetStatus sets the "status" field.
func (u *RoutingArtifactVersionUpsertBulk) SetStatus(v string) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateStatus() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetSchemaVersion sets the "schema_version" field.
func (u *RoutingArtifactVersionUpsertBulk) SetSchemaVersion(v string) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetSchemaVersion(v)
	})
}

// UpdateSchemaVersion sets the "schema_version" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateSchemaVersion() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateSchemaVersion()
	})
}

// SetChecksum sets the "checksum" field.
func (u *RoutingArtifactVersionUpsertBulk) SetChecksum(v string) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateChecksum() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateChecksum()
	})
}

// SetPayload sets the "payload" field.
func (u *RoutingArtifactVersionUpsertBulk) SetPayload(v jsontext.Value) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdatePayload() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *RoutingArtifactVersionUpsertBulk) ClearPayload() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearPayload()
	})
}

// SetDependencies sets the "dependencies" field.
func (u *RoutingArtifactVersionUpsertBulk) SetDependencies(v jsontext.Value) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetDependencies(v)
	})
}

// UpdateDependencies sets the "dependencies" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateDependencies() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateDependencies()
	})
}

// ClearDependencies clears the value of the "dependencies" field.
func (u *RoutingArtifactVersionUpsertBulk) ClearDependencies() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearDependencies()
	})
}

// SetLineage sets the "lineage" field.
func (u *RoutingArtifactVersionUpsertBulk) SetLineage(v jsontext.Value) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetLineage(v)
	})
}

// UpdateLineage sets the "lineage" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateLineage() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateLineage()
	})
}

// ClearLineage clears the value of the "lineage" field.
func (u *RoutingArtifactVersionUpsertBulk) ClearLineage() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearLineage()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *RoutingArtifactVersionUpsertBulk) SetCreatedBy(v int64) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateCreatedBy() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *RoutingArtifactVersionUpsertBulk) ClearCreatedBy() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearCreatedBy()
	})
}

// SetActivatedAt sets the "activated_at" field.
func (u *RoutingArtifactVersionUpsertBulk) SetActivatedAt(v time.Time) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetActivatedAt(v)
	})
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateActivatedAt() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateActivatedAt()
	})
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (u *RoutingArtifactVersionUpsertBulk) ClearActivatedAt() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearActivatedAt()
	})
}

// SetRetiredAt sets the "retired_at" field.
func (u *RoutingArtifactVersionUpsertBulk) SetRetiredAt(v time.Time) *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.SetRetiredAt(v)
	})
}

// UpdateRetiredAt sets the "retired_at" field to the value that was provided on create.
func (u *RoutingArtifactVersionUpsertBulk) UpdateRetiredAt() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.UpdateRetiredAt()
	})
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (u *RoutingArtifactVersionUpsertBulk) ClearRetiredAt() *RoutingArtifactVersionUpsertBulk {
	return u.Update(func(s *RoutingArtifactVersionUpsert) {
		s.ClearRetiredAt()
	})
}

// Exec executes the query.
func (u *RoutingArtifactVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RoutingArtifactVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RoutingArtifactVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RoutingArtifactVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
