// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/routingattempt"
)

// RoutingAttemptDelete is the builder for deleting a RoutingAttempt entity.
type RoutingAttemptDelete struct {
	config
	hooks    []Hook
	mutation *RoutingAttemptMutation
}

// Where appends a list predicates to the RoutingAttemptDelete builder.
func (_d *RoutingAttemptDelete) Where(ps ...predicate.RoutingAttempt) *RoutingAttemptDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RoutingAttemptDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RoutingAttemptDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RoutingAttemptDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(routingattempt.Table, sqlgraph.NewFieldSpec(routingattempt.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RoutingAttemptDeleteOne is the builder for deleting a single RoutingAttempt entity.
type RoutingAttemptDeleteOne struct {
	_d *RoutingAttemptDelete
}

// Where appends a list predicates to the RoutingAttemptDelete builder.
func (_d *RoutingAttemptDeleteOne) Where(ps ...predicate.RoutingAttempt) *RoutingAttemptDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RoutingAttemptDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{routingattempt.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RoutingAttemptDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
