// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/routingartifactversion"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RoutingArtifactVersionUpdate is the builder for updating RoutingArtifactVersion entities.
type RoutingArtifactVersionUpdate struct {
	config
	hooks    []Hook
	mutation *RoutingArtifactVersionMutation
}

// Where appends a list predicates to the RoutingArtifactVersionUpdate builder.
func (_u *RoutingArtifactVersionUpdate) Where(ps ...predicate.RoutingArtifactVersion) *RoutingArtifactVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetArtifactKind sets the "artifact_kind" field.
func (_u *RoutingArtifactVersionUpdate) SetArtifactKind(v string) *RoutingArtifactVersionUpdate {
	_u.mutation.SetArtifactKind(v)
	return _u
}

// SetNillableArtifactKind sets the "artifact_kind" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillableArtifactKind(v *string) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetArtifactKind(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *RoutingArtifactVersionUpdate) SetVersion(v string) *RoutingArtifactVersionUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillableVersion(v *string) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetParentVersion sets the "parent_version" field.
func (_u *RoutingArtifactVersionUpdate) SetParentVersion(v string) *RoutingArtifactVersionUpdate {
	_u.mutation.SetParentVersion(v)
	return _u
}

// SetNillableParentVersion sets the "parent_version" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillableParentVersion(v *string) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetParentVersion(*v)
	}
	return _u
}

// ClearParentVersion clears the value of the "parent_version" field.
func (_u *RoutingArtifactVersionUpdate) ClearParentVersion() *RoutingArtifactVersionUpdate {
	_u.mutation.ClearParentVersion()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *RoutingArtifactVersionUpdate) SetPlatform(v string) *RoutingArtifactVersionUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillablePlatform(v *string) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetModelFamily sets the "model_family" field.
func (_u *RoutingArtifactVersionUpdate) SetModelFamily(v string) *RoutingArtifactVersionUpdate {
	_u.mutation.SetModelFamily(v)
	return _u
}

// SetNillableModelFamily sets the "model_family" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillableModelFamily(v *string) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetModelFamily(*v)
	}
	return _u
}

// SetEndpointKind sets the "endpoint_kind" field.
func (_u *RoutingArtifactVersionUpdate) SetEndpointKind(v string) *RoutingArtifactVersionUpdate {
	_u.mutation.SetEndpointKind(v)
	return _u
}

// SetNillableEndpointKind sets the "endpoint_kind" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillableEndpointKind(v *string) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetEndpointKind(*v)
	}
	return _u
}

// SetPreference sets the "preference" field.
func (_u *RoutingArtifactVersionUpdate) SetPreference(v string) *RoutingArtifactVersionUpdate {
	_u.mutation.SetPreference(v)
	return _u
}

// SetNillablePreference sets the "preference" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillablePreference(v *string) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetPreference(*v)
	}
	return _u
}

// ClearPreference clears the value of the "preference" field.
func (_u *RoutingArtifactVersionUpdate) ClearPreference() *RoutingArtifactVersionUpdate {
	_u.mutation.ClearPreference()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RoutingArtifactVersionUpdate) SetStatus(v string) *RoutingArtifactVersionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillableStatus(v *string) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSchemaVersion sets the "schema_version" field.
func (_u *RoutingArtifactVersionUpdate) SetSchemaVersion(v string) *RoutingArtifactVersionUpdate {
	_u.mutation.SetSchemaVersion(v)
	return _u
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillableSchemaVersion(v *string) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetSchemaVersion(*v)
	}
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *RoutingArtifactVersionUpdate) SetChecksum(v string) *RoutingArtifactVersionUpdate {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillableChecksum(v *string) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *RoutingArtifactVersionUpdate) SetPayload(v jsontext.Value) *RoutingArtifactVersionUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// AppendPayload appends value to the "payload" field.
func (_u *RoutingArtifactVersionUpdate) AppendPayload(v jsontext.Value) *RoutingArtifactVersionUpdate {
	_u.mutation.AppendPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *RoutingArtifactVersionUpdate) ClearPayload() *RoutingArtifactVersionUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetDependencies sets the "dependencies" field.
func (_u *RoutingArtifactVersionUpdate) SetDependencies(v jsontext.Value) *RoutingArtifactVersionUpdate {
	_u.mutation.SetDependencies(v)
	return _u
}

// AppendDependencies appends value to the "dependencies" field.
func (_u *RoutingArtifactVersionUpdate) AppendDependencies(v jsontext.Value) *RoutingArtifactVersionUpdate {
	_u.mutation.AppendDependencies(v)
	return _u
}

// ClearDependencies clears the value of the "dependencies" field.
func (_u *RoutingArtifactVersionUpdate) ClearDependencies() *RoutingArtifactVersionUpdate {
	_u.mutation.ClearDependencies()
	return _u
}

// SetLineage sets the "lineage" field.
func (_u *RoutingArtifactVersionUpdate) SetLineage(v jsontext.Value) *RoutingArtifactVersionUpdate {
	_u.mutation.SetLineage(v)
	return _u
}

// AppendLineage appends value to the "lineage" field.
func (_u *RoutingArtifactVersionUpdate) AppendLineage(v jsontext.Value) *RoutingArtifactVersionUpdate {
	_u.mutation.AppendLineage(v)
	return _u
}

// ClearLineage clears the value of the "lineage" field.
func (_u *RoutingArtifactVersionUpdate) ClearLineage() *RoutingArtifactVersionUpdate {
	_u.mutation.ClearLineage()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *RoutingArtifactVersionUpdate) SetCreatedBy(v int64) *RoutingArtifactVersionUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillableCreatedBy(v *int64) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *RoutingArtifactVersionUpdate) ClearCreatedBy() *RoutingArtifactVersionUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *RoutingArtifactVersionUpdate) SetActivatedAt(v time.Time) *RoutingArtifactVersionUpdate {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillableActivatedAt(v *time.Time) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *RoutingArtifactVersionUpdate) ClearActivatedAt() *RoutingArtifactVersionUpdate {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetRetiredAt sets the "retired_at" field.
func (_u *RoutingArtifactVersionUpdate) SetRetiredAt(v time.Time) *RoutingArtifactVersionUpdate {
	_u.mutation.SetRetiredAt(v)
	return _u
}

// SetNillableRetiredAt sets the "retired_at" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillableRetiredAt(v *time.Time) *RoutingArtifactVersionUpdate {
	if v != nil {
		_u.SetRetiredAt(*v)
	}
	return _u
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (_u *RoutingArtifactVersionUpdate) ClearRetiredAt() *RoutingArtifactVersionUpdate {
	_u.mutation.ClearRetiredAt()
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *RoutingArtifactVersionUpdate) SetCreatorID(id int64) *RoutingArtifactVersionUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_u *RoutingArtifactVersionUpdate) SetNillableCreatorID(id *int64) *RoutingArtifactVersionUpdate {
	if id != nil {
		_u = _u.SetCreatorID(*id)
	}
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *RoutingArtifactVersionUpdate) SetCreator(v *User) *RoutingArtifactVersionUpdate {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the RoutingArtifactVersionMutation object of the builder.
func (_u *RoutingArtifactVersionUpdate) Mutation() *RoutingArtifactVersionMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *RoutingArtifactVersionUpdate) ClearCreator() *RoutingArtifactVersionUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoutingArtifactVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoutingArtifactVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoutingArtifactVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoutingArtifactVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoutingArtifactVersionUpdate) check() error {
	if v, ok := _u.mutation.ArtifactKind(); ok {
		if err := routingartifactversion.ArtifactKindValidator(v); err != nil {
			return &ValidationError{Name: "artifact_kind", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.artifact_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := routingartifactversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParentVersion(); ok {
		if err := routingartifactversion.ParentVersionValidator(v); err != nil {
			return &ValidationError{Name: "parent_version", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.parent_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := routingartifactversion.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelFamily(); ok {
		if err := routingartifactversion.ModelFamilyValidator(v); err != nil {
			return &ValidationError{Name: "model_family", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.model_family": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EndpointKind(); ok {
		if err := routingartifactversion.EndpointKindValidator(v); err != nil {
			return &ValidationError{Name: "endpoint_kind", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.endpoint_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Preference(); ok {
		if err := routingartifactversion.PreferenceValidator(v); err != nil {
			return &ValidationError{Name: "preference", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.preference": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := routingartifactversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SchemaVersion(); ok {
		if err := routingartifactversion.SchemaVersionValidator(v); err != nil {
			return &ValidationError{Name: "schema_version", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.schema_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Checksum(); ok {
		if err := routingartifactversion.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.checksum": %w`, err)}
		}
	}
	return nil
}

func (_u *RoutingArtifactVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(routingartifactversion.Table, routingartifactversion.Columns, sqlgraph.NewFieldSpec(routingartifactversion.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ArtifactKind(); ok {
		_spec.SetField(routingartifactversion.FieldArtifactKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(routingartifactversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentVersion(); ok {
		_spec.SetField(routingartifactversion.FieldParentVersion, field.TypeString, value)
	}
	if _u.mutation.ParentVersionCleared() {
		_spec.ClearField(routingartifactversion.FieldParentVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(routingartifactversion.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelFamily(); ok {
		_spec.SetField(routingartifactversion.FieldModelFamily, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndpointKind(); ok {
		_spec.SetField(routingartifactversion.FieldEndpointKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Preference(); ok {
		_spec.SetField(routingartifactversion.FieldPreference, field.TypeString, value)
	}
	if _u.mutation.PreferenceCleared() {
		_spec.ClearField(routingartifactversion.FieldPreference, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(routingartifactversion.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SchemaVersion(); ok {
		_spec.SetField(routingartifactversion.FieldSchemaVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(routingartifactversion.FieldChecksum, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(routingartifactversion.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingartifactversion.FieldPayload, value)
		})
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(routingartifactversion.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Dependencies(); ok {
		_spec.SetField(routingartifactversion.FieldDependencies, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDependencies(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingartifactversion.FieldDependencies, value)
		})
	}
	if _u.mutation.DependenciesCleared() {
		_spec.ClearField(routingartifactversion.FieldDependencies, field.TypeJSON)
	}
	if value, ok := _u.mutation.Lineage(); ok {
		_spec.SetField(routingartifactversion.FieldLineage, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLineage(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingartifactversion.FieldLineage, value)
		})
	}
	if _u.mutation.LineageCleared() {
		_spec.ClearField(routingartifactversion.FieldLineage, field.TypeJSON)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(routingartifactversion.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(routingartifactversion.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RetiredAt(); ok {
		_spec.SetField(routingartifactversion.FieldRetiredAt, field.TypeTime, value)
	}
	if _u.mutation.RetiredAtCleared() {
		_spec.ClearField(routingartifactversion.FieldRetiredAt, field.TypeTime)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   routingartifactversion.CreatorTable,
			Columns: []string{routingartifactversion.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   routingartifactversion.CreatorTable,
			Columns: []string{routingartifactversion.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{routingartifactversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoutingArtifactVersionUpdateOne is the builder for updating a single RoutingArtifactVersion entity.
type RoutingArtifactVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoutingArtifactVersionMutation
}

// SetArtifactKind sets the "artifact_kind" field.
func (_u *RoutingArtifactVersionUpdateOne) SetArtifactKind(v string) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetArtifactKind(v)
	return _u
}

// SetNillableArtifactKind sets the "artifact_kind" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillableArtifactKind(v *string) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetArtifactKind(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *RoutingArtifactVersionUpdateOne) SetVersion(v string) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillableVersion(v *string) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetParentVersion sets the "parent_version" field.
func (_u *RoutingArtifactVersionUpdateOne) SetParentVersion(v string) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetParentVersion(v)
	return _u
}

// SetNillableParentVersion sets the "parent_version" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillableParentVersion(v *string) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetParentVersion(*v)
	}
	return _u
}

// ClearParentVersion clears the value of the "parent_version" field.
func (_u *RoutingArtifactVersionUpdateOne) ClearParentVersion() *RoutingArtifactVersionUpdateOne {
	_u.mutation.ClearParentVersion()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *RoutingArtifactVersionUpdateOne) SetPlatform(v string) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillablePlatform(v *string) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetModelFamily sets the "model_family" field.
func (_u *RoutingArtifactVersionUpdateOne) SetModelFamily(v string) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetModelFamily(v)
	return _u
}

// SetNillableModelFamily sets the "model_family" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillableModelFamily(v *string) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetModelFamily(*v)
	}
	return _u
}

// SetEndpointKind sets the "endpoint_kind" field.
func (_u *RoutingArtifactVersionUpdateOne) SetEndpointKind(v string) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetEndpointKind(v)
	return _u
}

// SetNillableEndpointKind sets the "endpoint_kind" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillableEndpointKind(v *string) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetEndpointKind(*v)
	}
	return _u
}

// SetPreference sets the "preference" field.
func (_u *RoutingArtifactVersionUpdateOne) SetPreference(v string) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetPreference(v)
	return _u
}

// SetNillablePreference sets the "preference" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillablePreference(v *string) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetPreference(*v)
	}
	return _u
}

// ClearPreference clears the value of the "preference" field.
func (_u *RoutingArtifactVersionUpdateOne) ClearPreference() *RoutingArtifactVersionUpdateOne {
	_u.mutation.ClearPreference()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RoutingArtifactVersionUpdateOne) SetStatus(v string) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillableStatus(v *string) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSchemaVersion sets the "schema_version" field.
func (_u *RoutingArtifactVersionUpdateOne) SetSchemaVersion(v string) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetSchemaVersion(v)
	return _u
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillableSchemaVersion(v *string) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetSchemaVersion(*v)
	}
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *RoutingArtifactVersionUpdateOne) SetChecksum(v string) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillableChecksum(v *string) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *RoutingArtifactVersionUpdateOne) SetPayload(v jsontext.Value) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// AppendPayload appends value to the "payload" field.
func (_u *RoutingArtifactVersionUpdateOne) AppendPayload(v jsontext.Value) *RoutingArtifactVersionUpdateOne {
	_u.mutation.AppendPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *RoutingArtifactVersionUpdateOne) ClearPayload() *RoutingArtifactVersionUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetDependencies sets the "dependencies" field.
func (_u *RoutingArtifactVersionUpdateOne) SetDependencies(v jsontext.Value) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetDependencies(v)
	return _u
}

// AppendDependencies appends value to the "dependencies" field.
func (_u *RoutingArtifactVersionUpdateOne) AppendDependencies(v jsontext.Value) *RoutingArtifactVersionUpdateOne {
	_u.mutation.AppendDependencies(v)
	return _u
}

// ClearDependencies clears the value of the "dependencies" field.
func (_u *RoutingArtifactVersionUpdateOne) ClearDependencies() *RoutingArtifactVersionUpdateOne {
	_u.mutation.ClearDependencies()
	return _u
}

// SetLineage sets the "lineage" field.
func (_u *RoutingArtifactVersionUpdateOne) SetLineage(v jsontext.Value) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetLineage(v)
	return _u
}

// AppendLineage appends value to the "lineage" field.
func (_u *RoutingArtifactVersionUpdateOne) AppendLineage(v jsontext.Value) *RoutingArtifactVersionUpdateOne {
	_u.mutation.AppendLineage(v)
	return _u
}

// ClearLineage clears the value of the "lineage" field.
func (_u *RoutingArtifactVersionUpdateOne) ClearLineage() *RoutingArtifactVersionUpdateOne {
	_u.mutation.ClearLineage()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *RoutingArtifactVersionUpdateOne) SetCreatedBy(v int64) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillableCreatedBy(v *int64) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *RoutingArtifactVersionUpdateOne) ClearCreatedBy() *RoutingArtifactVersionUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *RoutingArtifactVersionUpdateOne) SetActivatedAt(v time.Time) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillableActivatedAt(v *time.Time) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *RoutingArtifactVersionUpdateOne) ClearActivatedAt() *RoutingArtifactVersionUpdateOne {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetRetiredAt sets the "retired_at" field.
func (_u *RoutingArtifactVersionUpdateOne) SetRetiredAt(v time.Time) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetRetiredAt(v)
	return _u
}

// SetNillableRetiredAt sets the "retired_at" field if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillableRetiredAt(v *time.Time) *RoutingArtifactVersionUpdateOne {
	if v != nil {
		_u.SetRetiredAt(*v)
	}
	return _u
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (_u *RoutingArtifactVersionUpdateOne) ClearRetiredAt() *RoutingArtifactVersionUpdateOne {
	_u.mutation.ClearRetiredAt()
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *RoutingArtifactVersionUpdateOne) SetCreatorID(id int64) *RoutingArtifactVersionUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_u *RoutingArtifactVersionUpdateOne) SetNillableCreatorID(id *int64) *RoutingArtifactVersionUpdateOne {
	if id != nil {
		_u = _u.SetCreatorID(*id)
	}
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *RoutingArtifactVersionUpdateOne) SetCreator(v *User) *RoutingArtifactVersionUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the RoutingArtifactVersionMutation object of the builder.
func (_u *RoutingArtifactVersionUpdateOne) Mutation() *RoutingArtifactVersionMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *RoutingArtifactVersionUpdateOne) ClearCreator() *RoutingArtifactVersionUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// Where appends a list predicates to the RoutingArtifactVersionUpdate builder.
func (_u *RoutingArtifactVersionUpdateOne) Where(ps ...predicate.RoutingArtifactVersion) *RoutingArtifactVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoutingArtifactVersionUpdateOne) Select(field string, fields ...string) *RoutingArtifactVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RoutingArtifactVersion entity.
func (_u *RoutingArtifactVersionUpdateOne) Save(ctx context.Context) (*RoutingArtifactVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoutingArtifactVersionUpdateOne) SaveX(ctx context.Context) *RoutingArtifactVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoutingArtifactVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoutingArtifactVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoutingArtifactVersionUpdateOne) check() error {
	if v, ok := _u.mutation.ArtifactKind(); ok {
		if err := routingartifactversion.ArtifactKindValidator(v); err != nil {
			return &ValidationError{Name: "artifact_kind", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.artifact_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := routingartifactversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParentVersion(); ok {
		if err := routingartifactversion.ParentVersionValidator(v); err != nil {
			return &ValidationError{Name: "parent_version", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.parent_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := routingartifactversion.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelFamily(); ok {
		if err := routingartifactversion.ModelFamilyValidator(v); err != nil {
			return &ValidationError{Name: "model_family", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.model_family": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EndpointKind(); ok {
		if err := routingartifactversion.EndpointKindValidator(v); err != nil {
			return &ValidationError{Name: "endpoint_kind", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.endpoint_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Preference(); ok {
		if err := routingartifactversion.PreferenceValidator(v); err != nil {
			return &ValidationError{Name: "preference", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.preference": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := routingartifactversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SchemaVersion(); ok {
		if err := routingartifactversion.SchemaVersionValidator(v); err != nil {
			return &ValidationError{Name: "schema_version", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.schema_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Checksum(); ok {
		if err := routingartifactversion.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "RoutingArtifactVersion.checksum": %w`, err)}
		}
	}
	return nil
}

func (_u *RoutingArtifactVersionUpdateOne) sqlSave(ctx context.Context) (_node *RoutingArtifactVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(routingartifactversion.Table, routingartifactversion.Columns, sqlgraph.NewFieldSpec(routingartifactversion.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RoutingArtifactVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, routingartifactversion.FieldID)
		for _, f := range fields {
			if !routingartifactversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != routingartifactversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ArtifactKind(); ok {
		_spec.SetField(routingartifactversion.FieldArtifactKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(routingartifactversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentVersion(); ok {
		_spec.SetField(routingartifactversion.FieldParentVersion, field.TypeString, value)
	}
	if _u.mutation.ParentVersionCleared() {
		_spec.ClearField(routingartifactversion.FieldParentVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(routingartifactversion.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelFamily(); ok {
		_spec.SetField(routingartifactversion.FieldModelFamily, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndpointKind(); ok {
		_spec.SetField(routingartifactversion.FieldEndpointKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Preference(); ok {
		_spec.SetField(routingartifactversion.FieldPreference, field.TypeString, value)
	}
	if _u.mutation.PreferenceCleared() {
		_spec.ClearField(routingartifactversion.FieldPreference, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(routingartifactversion.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SchemaVersion(); ok {
		_spec.SetField(routingartifactversion.FieldSchemaVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(routingartifactversion.FieldChecksum, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(routingartifactversion.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingartifactversion.FieldPayload, value)
		})
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(routingartifactversion.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Dependencies(); ok {
		_spec.SetField(routingartifactversion.FieldDependencies, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDependencies(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingartifactversion.FieldDependencies, value)
		})
	}
	if _u.mutation.DependenciesCleared() {
		_spec.ClearField(routingartifactversion.FieldDependencies, field.TypeJSON)
	}
	if value, ok := _u.mutation.Lineage(); ok {
		_spec.SetField(routingartifactversion.FieldLineage, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLineage(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingartifactversion.FieldLineage, value)
		})
	}
	if _u.mutation.LineageCleared() {
		_spec.ClearField(routingartifactversion.FieldLineage, field.TypeJSON)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(routingartifactversion.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(routingartifactversion.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RetiredAt(); ok {
		_spec.SetField(routingartifactversion.FieldRetiredAt, field.TypeTime, value)
	}
	if _u.mutation.RetiredAtCleared() {
		_spec.ClearField(routingartifactversion.FieldRetiredAt, field.TypeTime)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   routingartifactversion.CreatorTable,
			Columns: []string{routingartifactversion.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   routingartifactversion.CreatorTable,
			Columns: []string{routingartifactversion.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RoutingArtifactVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{routingartifactversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
