// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportnotificationoutbox"
)

// SupportNotificationOutboxUpdate is the builder for updating SupportNotificationOutbox entities.
type SupportNotificationOutboxUpdate struct {
	config
	hooks    []Hook
	mutation *SupportNotificationOutboxMutation
}

// Where appends a list predicates to the SupportNotificationOutboxUpdate builder.
func (_u *SupportNotificationOutboxUpdate) Where(ps ...predicate.SupportNotificationOutbox) *SupportNotificationOutboxUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *SupportNotificationOutboxUpdate) SetEventType(v string) *SupportNotificationOutboxUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdate) SetNillableEventType(v *string) *SupportNotificationOutboxUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *SupportNotificationOutboxUpdate) SetTicketID(v int64) *SupportNotificationOutboxUpdate {
	_u.mutation.ResetTicketID()
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdate) SetNillableTicketID(v *int64) *SupportNotificationOutboxUpdate {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// AddTicketID adds value to the "ticket_id" field.
func (_u *SupportNotificationOutboxUpdate) AddTicketID(v int64) *SupportNotificationOutboxUpdate {
	_u.mutation.AddTicketID(v)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *SupportNotificationOutboxUpdate) SetMessageID(v int64) *SupportNotificationOutboxUpdate {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdate) SetNillableMessageID(v *int64) *SupportNotificationOutboxUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *SupportNotificationOutboxUpdate) AddMessageID(v int64) *SupportNotificationOutboxUpdate {
	_u.mutation.AddMessageID(v)
	return _u
}

// ClearMessageID clears the value of the "message_id" field.
func (_u *SupportNotificationOutboxUpdate) ClearMessageID() *SupportNotificationOutboxUpdate {
	_u.mutation.ClearMessageID()
	return _u
}

// SetTargetAdminID sets the "target_admin_id" field.
func (_u *SupportNotificationOutboxUpdate) SetTargetAdminID(v int64) *SupportNotificationOutboxUpdate {
	_u.mutation.ResetTargetAdminID()
	_u.mutation.SetTargetAdminID(v)
	return _u
}

// SetNillableTargetAdminID sets the "target_admin_id" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdate) SetNillableTargetAdminID(v *int64) *SupportNotificationOutboxUpdate {
	if v != nil {
		_u.SetTargetAdminID(*v)
	}
	return _u
}

// AddTargetAdminID adds value to the "target_admin_id" field.
func (_u *SupportNotificationOutboxUpdate) AddTargetAdminID(v int64) *SupportNotificationOutboxUpdate {
	_u.mutation.AddTargetAdminID(v)
	return _u
}

// SetTelegramMessageID sets the "telegram_message_id" field.
func (_u *SupportNotificationOutboxUpdate) SetTelegramMessageID(v int64) *SupportNotificationOutboxUpdate {
	_u.mutation.ResetTelegramMessageID()
	_u.mutation.SetTelegramMessageID(v)
	return _u
}

// SetNillableTelegramMessageID sets the "telegram_message_id" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdate) SetNillableTelegramMessageID(v *int64) *SupportNotificationOutboxUpdate {
	if v != nil {
		_u.SetTelegramMessageID(*v)
	}
	return _u
}

// AddTelegramMessageID adds value to the "telegram_message_id" field.
func (_u *SupportNotificationOutboxUpdate) AddTelegramMessageID(v int64) *SupportNotificationOutboxUpdate {
	_u.mutation.AddTelegramMessageID(v)
	return _u
}

// ClearTelegramMessageID clears the value of the "telegram_message_id" field.
func (_u *SupportNotificationOutboxUpdate) ClearTelegramMessageID() *SupportNotificationOutboxUpdate {
	_u.mutation.ClearTelegramMessageID()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *SupportNotificationOutboxUpdate) SetPayload(v string) *SupportNotificationOutboxUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdate) SetNillablePayload(v *string) *SupportNotificationOutboxUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportNotificationOutboxUpdate) SetStatus(v string) *SupportNotificationOutboxUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdate) SetNillableStatus(v *string) *SupportNotificationOutboxUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *SupportNotificationOutboxUpdate) SetAttemptCount(v int) *SupportNotificationOutboxUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdate) SetNillableAttemptCount(v *int) *SupportNotificationOutboxUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *SupportNotificationOutboxUpdate) AddAttemptCount(v int) *SupportNotificationOutboxUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *SupportNotificationOutboxUpdate) SetNextAttemptAt(v time.Time) *SupportNotificationOutboxUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdate) SetNillableNextAttemptAt(v *time.Time) *SupportNotificationOutboxUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *SupportNotificationOutboxUpdate) SetLockedAt(v time.Time) *SupportNotificationOutboxUpdate {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdate) SetNillableLockedAt(v *time.Time) *SupportNotificationOutboxUpdate {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *SupportNotificationOutboxUpdate) ClearLockedAt() *SupportNotificationOutboxUpdate {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *SupportNotificationOutboxUpdate) SetLastError(v string) *SupportNotificationOutboxUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdate) SetNillableLastError(v *string) *SupportNotificationOutboxUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *SupportNotificationOutboxUpdate) ClearLastError() *SupportNotificationOutboxUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *SupportNotificationOutboxUpdate) SetSentAt(v time.Time) *SupportNotificationOutboxUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdate) SetNillableSentAt(v *time.Time) *SupportNotificationOutboxUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *SupportNotificationOutboxUpdate) ClearSentAt() *SupportNotificationOutboxUpdate {
	_u.mutation.ClearSentAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportNotificationOutboxUpdate) SetUpdatedAt(v time.Time) *SupportNotificationOutboxUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SupportNotificationOutboxMutation object of the builder.
func (_u *SupportNotificationOutboxUpdate) Mutation() *SupportNotificationOutboxMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportNotificationOutboxUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportNotificationOutboxUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportNotificationOutboxUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportNotificationOutboxUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportNotificationOutboxUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportnotificationoutbox.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportNotificationOutboxUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := supportnotificationoutbox.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "SupportNotificationOutbox.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportnotificationoutbox.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportNotificationOutbox.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportNotificationOutboxUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportnotificationoutbox.Table, supportnotificationoutbox.Columns, sqlgraph.NewFieldSpec(supportnotificationoutbox.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(supportnotificationoutbox.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TicketID(); ok {
		_spec.SetField(supportnotificationoutbox.FieldTicketID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTicketID(); ok {
		_spec.AddField(supportnotificationoutbox.FieldTicketID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(supportnotificationoutbox.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(supportnotificationoutbox.FieldMessageID, field.TypeInt64, value)
	}
	if _u.mutation.MessageIDCleared() {
		_spec.ClearField(supportnotificationoutbox.FieldMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.TargetAdminID(); ok {
		_spec.SetField(supportnotificationoutbox.FieldTargetAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetAdminID(); ok {
		_spec.AddField(supportnotificationoutbox.FieldTargetAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TelegramMessageID(); ok {
		_spec.SetField(supportnotificationoutbox.FieldTelegramMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegramMessageID(); ok {
		_spec.AddField(supportnotificationoutbox.FieldTelegramMessageID, field.TypeInt64, value)
	}
	if _u.mutation.TelegramMessageIDCleared() {
		_spec.ClearField(supportnotificationoutbox.FieldTelegramMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(supportnotificationoutbox.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportnotificationoutbox.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(supportnotificationoutbox.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(supportnotificationoutbox.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(supportnotificationoutbox.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(supportnotificationoutbox.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(supportnotificationoutbox.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(supportnotificationoutbox.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(supportnotificationoutbox.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(supportnotificationoutbox.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(supportnotificationoutbox.FieldSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportnotificationoutbox.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportnotificationoutbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportNotificationOutboxUpdateOne is the builder for updating a single SupportNotificationOutbox entity.
type SupportNotificationOutboxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportNotificationOutboxMutation
}

// SetEventType sets the "event_type" field.
func (_u *SupportNotificationOutboxUpdateOne) SetEventType(v string) *SupportNotificationOutboxUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdateOne) SetNillableEventType(v *string) *SupportNotificationOutboxUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *SupportNotificationOutboxUpdateOne) SetTicketID(v int64) *SupportNotificationOutboxUpdateOne {
	_u.mutation.ResetTicketID()
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdateOne) SetNillableTicketID(v *int64) *SupportNotificationOutboxUpdateOne {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// AddTicketID adds value to the "ticket_id" field.
func (_u *SupportNotificationOutboxUpdateOne) AddTicketID(v int64) *SupportNotificationOutboxUpdateOne {
	_u.mutation.AddTicketID(v)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *SupportNotificationOutboxUpdateOne) SetMessageID(v int64) *SupportNotificationOutboxUpdateOne {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdateOne) SetNillableMessageID(v *int64) *SupportNotificationOutboxUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *SupportNotificationOutboxUpdateOne) AddMessageID(v int64) *SupportNotificationOutboxUpdateOne {
	_u.mutation.AddMessageID(v)
	return _u
}

// ClearMessageID clears the value of the "message_id" field.
func (_u *SupportNotificationOutboxUpdateOne) ClearMessageID() *SupportNotificationOutboxUpdateOne {
	_u.mutation.ClearMessageID()
	return _u
}

// SetTargetAdminID sets the "target_admin_id" field.
func (_u *SupportNotificationOutboxUpdateOne) SetTargetAdminID(v int64) *SupportNotificationOutboxUpdateOne {
	_u.mutation.ResetTargetAdminID()
	_u.mutation.SetTargetAdminID(v)
	return _u
}

// SetNillableTargetAdminID sets the "target_admin_id" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdateOne) SetNillableTargetAdminID(v *int64) *SupportNotificationOutboxUpdateOne {
	if v != nil {
		_u.SetTargetAdminID(*v)
	}
	return _u
}

// AddTargetAdminID adds value to the "target_admin_id" field.
func (_u *SupportNotificationOutboxUpdateOne) AddTargetAdminID(v int64) *SupportNotificationOutboxUpdateOne {
	_u.mutation.AddTargetAdminID(v)
	return _u
}

// SetTelegramMessageID sets the "telegram_message_id" field.
func (_u *SupportNotificationOutboxUpdateOne) SetTelegramMessageID(v int64) *SupportNotificationOutboxUpdateOne {
	_u.mutation.ResetTelegramMessageID()
	_u.mutation.SetTelegramMessageID(v)
	return _u
}

// SetNillableTelegramMessageID sets the "telegram_message_id" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdateOne) SetNillableTelegramMessageID(v *int64) *SupportNotificationOutboxUpdateOne {
	if v != nil {
		_u.SetTelegramMessageID(*v)
	}
	return _u
}

// AddTelegramMessageID adds value to the "telegram_message_id" field.
func (_u *SupportNotificationOutboxUpdateOne) AddTelegramMessageID(v int64) *SupportNotificationOutboxUpdateOne {
	_u.mutation.AddTelegramMessageID(v)
	return _u
}

// ClearTelegramMessageID clears the value of the "telegram_message_id" field.
func (_u *SupportNotificationOutboxUpdateOne) ClearTelegramMessageID() *SupportNotificationOutboxUpdateOne {
	_u.mutation.ClearTelegramMessageID()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *SupportNotificationOutboxUpdateOne) SetPayload(v string) *SupportNotificationOutboxUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdateOne) SetNillablePayload(v *string) *SupportNotificationOutboxUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportNotificationOutboxUpdateOne) SetStatus(v string) *SupportNotificationOutboxUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdateOne) SetNillableStatus(v *string) *SupportNotificationOutboxUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *SupportNotificationOutboxUpdateOne) SetAttemptCount(v int) *SupportNotificationOutboxUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdateOne) SetNillableAttemptCount(v *int) *SupportNotificationOutboxUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *SupportNotificationOutboxUpdateOne) AddAttemptCount(v int) *SupportNotificationOutboxUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *SupportNotificationOutboxUpdateOne) SetNextAttemptAt(v time.Time) *SupportNotificationOutboxUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdateOne) SetNillableNextAttemptAt(v *time.Time) *SupportNotificationOutboxUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *SupportNotificationOutboxUpdateOne) SetLockedAt(v time.Time) *SupportNotificationOutboxUpdateOne {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdateOne) SetNillableLockedAt(v *time.Time) *SupportNotificationOutboxUpdateOne {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *SupportNotificationOutboxUpdateOne) ClearLockedAt() *SupportNotificationOutboxUpdateOne {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *SupportNotificationOutboxUpdateOne) SetLastError(v string) *SupportNotificationOutboxUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdateOne) SetNillableLastError(v *string) *SupportNotificationOutboxUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *SupportNotificationOutboxUpdateOne) ClearLastError() *SupportNotificationOutboxUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *SupportNotificationOutboxUpdateOne) SetSentAt(v time.Time) *SupportNotificationOutboxUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *SupportNotificationOutboxUpdateOne) SetNillableSentAt(v *time.Time) *SupportNotificationOutboxUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *SupportNotificationOutboxUpdateOne) ClearSentAt() *SupportNotificationOutboxUpdateOne {
	_u.mutation.ClearSentAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportNotificationOutboxUpdateOne) SetUpdatedAt(v time.Time) *SupportNotificationOutboxUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SupportNotificationOutboxMutation object of the builder.
func (_u *SupportNotificationOutboxUpdateOne) Mutation() *SupportNotificationOutboxMutation {
	return _u.mutation
}

// Where appends a list predicates to the SupportNotificationOutboxUpdate builder.
func (_u *SupportNotificationOutboxUpdateOne) Where(ps ...predicate.SupportNotificationOutbox) *SupportNotificationOutboxUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportNotificationOutboxUpdateOne) Select(field string, fields ...string) *SupportNotificationOutboxUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportNotificationOutbox entity.
func (_u *SupportNotificationOutboxUpdateOne) Save(ctx context.Context) (*SupportNotificationOutbox, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportNotificationOutboxUpdateOne) SaveX(ctx context.Context) *SupportNotificationOutbox {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportNotificationOutboxUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportNotificationOutboxUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportNotificationOutboxUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportnotificationoutbox.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportNotificationOutboxUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := supportnotificationoutbox.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "SupportNotificationOutbox.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportnotificationoutbox.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportNotificationOutbox.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportNotificationOutboxUpdateOne) sqlSave(ctx context.Context) (_node *SupportNotificationOutbox, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportnotificationoutbox.Table, supportnotificationoutbox.Columns, sqlgraph.NewFieldSpec(supportnotificationoutbox.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportNotificationOutbox.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportnotificationoutbox.FieldID)
		for _, f := range fields {
			if !supportnotificationoutbox.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportnotificationoutbox.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(supportnotificationoutbox.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TicketID(); ok {
		_spec.SetField(supportnotificationoutbox.FieldTicketID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTicketID(); ok {
		_spec.AddField(supportnotificationoutbox.FieldTicketID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(supportnotificationoutbox.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(supportnotificationoutbox.FieldMessageID, field.TypeInt64, value)
	}
	if _u.mutation.MessageIDCleared() {
		_spec.ClearField(supportnotificationoutbox.FieldMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.TargetAdminID(); ok {
		_spec.SetField(supportnotificationoutbox.FieldTargetAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetAdminID(); ok {
		_spec.AddField(supportnotificationoutbox.FieldTargetAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TelegramMessageID(); ok {
		_spec.SetField(supportnotificationoutbox.FieldTelegramMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegramMessageID(); ok {
		_spec.AddField(supportnotificationoutbox.FieldTelegramMessageID, field.TypeInt64, value)
	}
	if _u.mutation.TelegramMessageIDCleared() {
		_spec.ClearField(supportnotificationoutbox.FieldTelegramMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(supportnotificationoutbox.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportnotificationoutbox.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(supportnotificationoutbox.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(supportnotificationoutbox.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(supportnotificationoutbox.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(supportnotificationoutbox.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(supportnotificationoutbox.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(supportnotificationoutbox.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(supportnotificationoutbox.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(supportnotificationoutbox.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(supportnotificationoutbox.FieldSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportnotificationoutbox.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SupportNotificationOutbox{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportnotificationoutbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
