// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/supportticketattachment"
)

// SupportTicketAttachmentCreate is the builder for creating a SupportTicketAttachment entity.
type SupportTicketAttachmentCreate struct {
	config
	mutation *SupportTicketAttachmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTicketID sets the "ticket_id" field.
func (_c *SupportTicketAttachmentCreate) SetTicketID(v int64) *SupportTicketAttachmentCreate {
	_c.mutation.SetTicketID(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *SupportTicketAttachmentCreate) SetMessageID(v int64) *SupportTicketAttachmentCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetUploaderID sets the "uploader_id" field.
func (_c *SupportTicketAttachmentCreate) SetUploaderID(v int64) *SupportTicketAttachmentCreate {
	_c.mutation.SetUploaderID(v)
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *SupportTicketAttachmentCreate) SetStorageKey(v string) *SupportTicketAttachmentCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetOriginalName sets the "original_name" field.
func (_c *SupportTicketAttachmentCreate) SetOriginalName(v string) *SupportTicketAttachmentCreate {
	_c.mutation.SetOriginalName(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *SupportTicketAttachmentCreate) SetContentType(v string) *SupportTicketAttachmentCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *SupportTicketAttachmentCreate) SetSize(v int64) *SupportTicketAttachmentCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetWidth sets the "width" field.
func (_c *SupportTicketAttachmentCreate) SetWidth(v int) *SupportTicketAttachmentCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetHeight sets the "height" field.
func (_c *SupportTicketAttachmentCreate) SetHeight(v int) *SupportTicketAttachmentCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *SupportTicketAttachmentCreate) SetSha256(v string) *SupportTicketAttachmentCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetHiddenAt sets the "hidden_at" field.
func (_c *SupportTicketAttachmentCreate) SetHiddenAt(v time.Time) *SupportTicketAttachmentCreate {
	_c.mutation.SetHiddenAt(v)
	return _c
}

// SetNillableHiddenAt sets the "hidden_at" field if the given value is not nil.
func (_c *SupportTicketAttachmentCreate) SetNillableHiddenAt(v *time.Time) *SupportTicketAttachmentCreate {
	if v != nil {
		_c.SetHiddenAt(*v)
	}
	return _c
}

// SetHiddenBy sets the "hidden_by" field.
func (_c *SupportTicketAttachmentCreate) SetHiddenBy(v int64) *SupportTicketAttachmentCreate {
	_c.mutation.SetHiddenBy(v)
	return _c
}

// SetNillableHiddenBy sets the "hidden_by" field if the given value is not nil.
func (_c *SupportTicketAttachmentCreate) SetNillableHiddenBy(v *int64) *SupportTicketAttachmentCreate {
	if v != nil {
		_c.SetHiddenBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupportTicketAttachmentCreate) SetCreatedAt(v time.Time) *SupportTicketAttachmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupportTicketAttachmentCreate) SetNillableCreatedAt(v *time.Time) *SupportTicketAttachmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the SupportTicketAttachmentMutation object of the builder.
func (_c *SupportTicketAttachmentCreate) Mutation() *SupportTicketAttachmentMutation {
	return _c.mutation
}

// Save creates the SupportTicketAttachment in the database.
func (_c *SupportTicketAttachmentCreate) Save(ctx context.Context) (*SupportTicketAttachment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupportTicketAttachmentCreate) SaveX(ctx context.Context) *SupportTicketAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportTicketAttachmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportTicketAttachmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupportTicketAttachmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := supportticketattachment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupportTicketAttachmentCreate) check() error {
	if _, ok := _c.mutation.TicketID(); !ok {
		return &ValidationError{Name: "ticket_id", err: errors.New(`ent: missing required field "SupportTicketAttachment.ticket_id"`)}
	}
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "SupportTicketAttachment.message_id"`)}
	}
	if _, ok := _c.mutation.UploaderID(); !ok {
		return &ValidationError{Name: "uploader_id", err: errors.New(`ent: missing required field "SupportTicketAttachment.uploader_id"`)}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "SupportTicketAttachment.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := supportticketattachment.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginalName(); !ok {
		return &ValidationError{Name: "original_name", err: errors.New(`ent: missing required field "SupportTicketAttachment.original_name"`)}
	}
	if v, ok := _c.mutation.OriginalName(); ok {
		if err := supportticketattachment.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.original_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "SupportTicketAttachment.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := supportticketattachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "SupportTicketAttachment.size"`)}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "SupportTicketAttachment.width"`)}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "SupportTicketAttachment.height"`)}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "SupportTicketAttachment.sha256"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := supportticketattachment.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupportTicketAttachment.created_at"`)}
	}
	return nil
}

func (_c *SupportTicketAttachmentCreate) sqlSave(ctx context.Context) (*SupportTicketAttachment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupportTicketAttachmentCreate) createSpec() (*SupportTicketAttachment, *sqlgraph.CreateSpec) {
	var (
		_node = &SupportTicketAttachment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supportticketattachment.Table, sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TicketID(); ok {
		_spec.SetField(supportticketattachment.FieldTicketID, field.TypeInt64, value)
		_node.TicketID = value
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(supportticketattachment.FieldMessageID, field.TypeInt64, value)
		_node.MessageID = value
	}
	if value, ok := _c.mutation.UploaderID(); ok {
		_spec.SetField(supportticketattachment.FieldUploaderID, field.TypeInt64, value)
		_node.UploaderID = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(supportticketattachment.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.OriginalName(); ok {
		_spec.SetField(supportticketattachment.FieldOriginalName, field.TypeString, value)
		_node.OriginalName = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(supportticketattachment.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(supportticketattachment.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(supportticketattachment.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(supportticketattachment.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(supportticketattachment.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.HiddenAt(); ok {
		_spec.SetField(supportticketattachment.FieldHiddenAt, field.TypeTime, value)
		_node.HiddenAt = &value
	}
	if value, ok := _c.mutation.HiddenBy(); ok {
		_spec.SetField(supportticketattachment.FieldHiddenBy, field.TypeInt64, value)
		_node.HiddenBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supportticketattachment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportTicketAttachment.Create().
//		SetTicketID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportTicketAttachmentUpsert) {
//			SetTicketID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportTicketAttachmentCreate) OnConflict(opts ...sql.ConflictOption) *SupportTicketAttachmentUpsertOne {
	_c.conflict = opts
	return &SupportTicketAttachmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportTicketAttachmentCreate) OnConflictColumns(columns ...string) *SupportTicketAttachmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportTicketAttachmentUpsertOne{
		create: _c,
	}
}

type (
	// SupportTicketAttachmentUpsertOne is the builder for "upsert"-ing
	//  one SupportTicketAttachment node.
	SupportTicketAttachmentUpsertOne struct {
		create *SupportTicketAttachmentCreate
	}

	// SupportTicketAttachmentUpsert is the "OnConflict" setter.
	SupportTicketAttachmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetTicketID sets the "ticket_id" field.
func (u *SupportTicketAttachmentUpsert) SetTicketID(v int64) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldTicketID, v)
	return u
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateTicketID() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldTicketID)
	return u
}

// AddTicketID adds v to the "ticket_id" field.
func (u *SupportTicketAttachmentUpsert) AddTicketID(v int64) *SupportTicketAttachmentUpsert {
	u.Add(supportticketattachment.FieldTicketID, v)
	return u
}

// SetMessageID sets the "message_id" field.
func (u *SupportTicketAttachmentUpsert) SetMessageID(v int64) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldMessageID, v)
	return u
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateMessageID() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldMessageID)
	return u
}

// AddMessageID adds v to the "message_id" field.
func (u *SupportTicketAttachmentUpsert) AddMessageID(v int64) *SupportTicketAttachmentUpsert {
	u.Add(supportticketattachment.FieldMessageID, v)
	return u
}

// SetUploaderID sets the "uploader_id" field.
func (u *SupportTicketAttachmentUpsert) SetUploaderID(v int64) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldUploaderID, v)
	return u
}

// UpdateUploaderID sets the "uploader_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateUploaderID() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldUploaderID)
	return u
}

// AddUploaderID adds v to the "uploader_id" field.
func (u *SupportTicketAttachmentUpsert) AddUploaderID(v int64) *SupportTicketAttachmentUpsert {
	u.Add(supportticketattachment.FieldUploaderID, v)
	return u
}

// SetStorageKey sets the "storage_key" field.
func (u *SupportTicketAttachmentUpsert) SetStorageKey(v string) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldStorageKey, v)
	return u
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateStorageKey() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldStorageKey)
	return u
}

// SetOriginalName sets the "original_name" field.
func (u *SupportTicketAttachmentUpsert) SetOriginalName(v string) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldOriginalName, v)
	return u
}

// UpdateOriginalName sets the "original_name" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateOriginalName() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldOriginalName)
	return u
}

// SetContentType sets the "content_type" field.
func (u *SupportTicketAttachmentUpsert) SetContentType(v string) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldContentType, v)
	return u
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateContentType() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldContentType)
	return u
}

// SetSize sets the "size" field.
func (u *SupportTicketAttachmentUpsert) SetSize(v int64) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateSize() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldSize)
	return u
}

// AddSize adds v to the "size" field.
func (u *SupportTicketAttachmentUpsert) AddSize(v int64) *SupportTicketAttachmentUpsert {
	u.Add(supportticketattachment.FieldSize, v)
	return u
}

// SetWidth sets the "width" field.
func (u *SupportTicketAttachmentUpsert) SetWidth(v int) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateWidth() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *SupportTicketAttachmentUpsert) AddWidth(v int) *SupportTicketAttachmentUpsert {
	u.Add(supportticketattachment.FieldWidth, v)
	return u
}

// SetHeight sets the "height" field.
func (u *SupportTicketAttachmentUpsert) SetHeight(v int) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateHeight() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *SupportTicketAttachmentUpsert) AddHeight(v int) *SupportTicketAttachmentUpsert {
	u.Add(supportticketattachment.FieldHeight, v)
	return u
}

// SetSha256 sets the "sha256" field.
func (u *SupportTicketAttachmentUpsert) SetSha256(v string) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldSha256, v)
	return u
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateSha256() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldSha256)
	return u
}

// SetHiddenAt sets the "hidden_at" field.
func (u *SupportTicketAttachmentUpsert) SetHiddenAt(v time.Time) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldHiddenAt, v)
	return u
}

// UpdateHiddenAt sets the "hidden_at" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateHiddenAt() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldHiddenAt)
	return u
}

// ClearHiddenAt clears the value of the "hidden_at" field.
func (u *SupportTicketAttachmentUpsert) ClearHiddenAt() *SupportTicketAttachmentUpsert {
	u.SetNull(supportticketattachment.FieldHiddenAt)
	return u
}

// SetHiddenBy sets the "hidden_by" field.
func (u *SupportTicketAttachmentUpsert) SetHiddenBy(v int64) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldHiddenBy, v)
	return u
}

// UpdateHiddenBy sets the "hidden_by" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateHiddenBy() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldHiddenBy)
	return u
}

// AddHiddenBy adds v to the "hidden_by" field.
func (u *SupportTicketAttachmentUpsert) AddHiddenBy(v int64) *SupportTicketAttachmentUpsert {
	u.Add(supportticketattachment.FieldHiddenBy, v)
	return u
}

// ClearHiddenBy clears the value of the "hidden_by" field.
func (u *SupportTicketAttachmentUpsert) ClearHiddenBy() *SupportTicketAttachmentUpsert {
	u.SetNull(supportticketattachment.FieldHiddenBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportTicketAttachmentUpsertOne) UpdateNewValues() *SupportTicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(supportticketattachment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupportTicketAttachmentUpsertOne) Ignore() *SupportTicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportTicketAttachmentUpsertOne) DoNothing() *SupportTicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportTicketAttachmentCreate.OnConflict
// documentation for more info.
func (u *SupportTicketAttachmentUpsertOne) Update(set func(*SupportTicketAttachmentUpsert)) *SupportTicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportTicketAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetTicketID sets the "ticket_id" field.
func (u *SupportTicketAttachmentUpsertOne) SetTicketID(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetTicketID(v)
	})
}

// AddTicketID adds v to the "ticket_id" field.
func (u *SupportTicketAttachmentUpsertOne) AddTicketID(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateTicketID() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateTicketID()
	})
}

// SetMessageID sets the "message_id" field.
func (u *SupportTicketAttachmentUpsertOne) SetMessageID(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetMessageID(v)
	})
}

// AddMessageID adds v to the "message_id" field.
func (u *SupportTicketAttachmentUpsertOne) AddMessageID(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateMessageID() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateMessageID()
	})
}

// SetUploaderID sets the "uploader_id" field.
func (u *SupportTicketAttachmentUpsertOne) SetUploaderID(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetUploaderID(v)
	})
}

// AddUploaderID adds v to the "uploader_id" field.
func (u *SupportTicketAttachmentUpsertOne) AddUploaderID(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddUploaderID(v)
	})
}

// UpdateUploaderID sets the "uploader_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateUploaderID() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateUploaderID()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *SupportTicketAttachmentUpsertOne) SetStorageKey(v string) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateStorageKey() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateStorageKey()
	})
}

// SetOriginalName sets the "original_name" field.
func (u *SupportTicketAttachmentUpsertOne) SetOriginalName(v string) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetOriginalName(v)
	})
}

// UpdateOriginalName sets the "original_name" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateOriginalName() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateOriginalName()
	})
}

// SetContentType sets the "content_type" field.
func (u *SupportTicketAttachmentUpsertOne) SetContentType(v string) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateContentType() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateContentType()
	})
}

// SetSize sets the "size" field.
func (u *SupportTicketAttachmentUpsertOne) SetSize(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *SupportTicketAttachmentUpsertOne) AddSize(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateSize() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateSize()
	})
}

// SetWidth sets the "width" field.
func (u *SupportTicketAttachmentUpsertOne) SetWidth(v int) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *SupportTicketAttachmentUpsertOne) AddWidth(v int) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateWidth() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *SupportTicketAttachmentUpsertOne) SetHeight(v int) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *SupportTicketAttachmentUpsertOne) AddHeight(v int) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateHeight() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateHeight()
	})
}

// SetSha256 sets the "sha256" field.
func (u *SupportTicketAttachmentUpsertOne) SetSha256(v string) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateSha256() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateSha256()
	})
}

// SetHiddenAt sets the "hidden_at" field.
func (u *SupportTicketAttachmentUpsertOne) SetHiddenAt(v time.Time) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetHiddenAt(v)
	})
}

// UpdateHiddenAt sets the "hidden_at" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateHiddenAt() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateHiddenAt()
	})
}

// ClearHiddenAt clears the value of the "hidden_at" field.
func (u *SupportTicketAttachmentUpsertOne) ClearHiddenAt() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearHiddenAt()
	})
}

// SetHiddenBy sets the "hidden_by" field.
func (u *SupportTicketAttachmentUpsertOne) SetHiddenBy(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetHiddenBy(v)
	})
}

// AddHiddenBy adds v to the "hidden_by" field.
func (u *SupportTicketAttachmentUpsertOne) AddHiddenBy(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddHiddenBy(v)
	})
}

// UpdateHiddenBy sets the "hidden_by" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateHiddenBy() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateHiddenBy()
	})
}

// ClearHiddenBy clears the value of the "hidden_by" field.
func (u *SupportTicketAttachmentUpsertOne) ClearHiddenBy() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearHiddenBy()
	})
}

// Exec executes the query.
func (u *SupportTicketAttachmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportTicketAttachmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportTicketAttachmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupportTicketAttachmentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupportTicketAttachmentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupportTicketAttachmentCreateBulk is the builder for creating many SupportTicketAttachment entities in bulk.
type SupportTicketAttachmentCreateBulk struct {
	config
	err      error
	builders []*SupportTicketAttachmentCreate
	conflict []sql.ConflictOption
}

// Save creates the SupportTicketAttachment entities in the database.
func (_c *SupportTicketAttachmentCreateBulk) Save(ctx context.Context) ([]*SupportTicketAttachment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupportTicketAttachment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupportTicketAttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupportTicketAttachmentCreateBulk) SaveX(ctx context.Context) []*SupportTicketAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportTicketAttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportTicketAttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportTicketAttachment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportTicketAttachmentUpsert) {
//			SetTicketID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportTicketAttachmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupportTicketAttachmentUpsertBulk {
	_c.conflict = opts
	return &SupportTicketAttachmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportTicketAttachmentCreateBulk) OnConflictColumns(columns ...string) *SupportTicketAttachmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportTicketAttachmentUpsertBulk{
		create: _c,
	}
}

// SupportTicketAttachmentUpsertBulk is the builder for "upsert"-ing
// a bulk of SupportTicketAttachment nodes.
type SupportTicketAttachmentUpsertBulk struct {
	create *SupportTicketAttachmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportTicketAttachmentUpsertBulk) UpdateNewValues() *SupportTicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(supportticketattachment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupportTicketAttachmentUpsertBulk) Ignore() *SupportTicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportTicketAttachmentUpsertBulk) DoNothing() *SupportTicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportTicketAttachmentCreateBulk.OnConflict
// documentation for more info.
func (u *SupportTicketAttachmentUpsertBulk) Update(set func(*SupportTicketAttachmentUpsert)) *SupportTicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportTicketAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetTicketID sets the "ticket_id" field.
func (u *SupportTicketAttachmentUpsertBulk) SetTicketID(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetTicketID(v)
	})
}

// AddTicketID adds v to the "ticket_id" field.
func (u *SupportTicketAttachmentUpsertBulk) AddTicketID(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateTicketID() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateTicketID()
	})
}

// SetMessageID sets the "message_id" field.
func (u *SupportTicketAttachmentUpsertBulk) SetMessageID(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetMessageID(v)
	})
}

// AddMessageID adds v to the "message_id" field.
func (u *SupportTicketAttachmentUpsertBulk) AddMessageID(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateMessageID() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateMessageID()
	})
}

// SetUploaderID sets the "uploader_id" field.
func (u *SupportTicketAttachmentUpsertBulk) SetUploaderID(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetUploaderID(v)
	})
}

// AddUploaderID adds v to the "uploader_id" field.
func (u *SupportTicketAttachmentUpsertBulk) AddUploaderID(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddUploaderID(v)
	})
}

// UpdateUploaderID sets the "uploader_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateUploaderID() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateUploaderID()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *SupportTicketAttachmentUpsertBulk) SetStorageKey(v string) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateStorageKey() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateStorageKey()
	})
}

// SetOriginalName sets the "original_name" field.
func (u *SupportTicketAttachmentUpsertBulk) SetOriginalName(v string) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetOriginalName(v)
	})
}

// UpdateOriginalName sets the "original_name" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateOriginalName() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateOriginalName()
	})
}

// SetContentType sets the "content_type" field.
func (u *SupportTicketAttachmentUpsertBulk) SetContentType(v string) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateContentType() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateContentType()
	})
}

// SetSize sets the "size" field.
func (u *SupportTicketAttachmentUpsertBulk) SetSize(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *SupportTicketAttachmentUpsertBulk) AddSize(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateSize() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateSize()
	})
}

// SetWidth sets the "width" field.
func (u *SupportTicketAttachmentUpsertBulk) SetWidth(v int) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *SupportTicketAttachmentUpsertBulk) AddWidth(v int) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateWidth() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *SupportTicketAttachmentUpsertBulk) SetHeight(v int) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *SupportTicketAttachmentUpsertBulk) AddHeight(v int) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateHeight() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateHeight()
	})
}

// SetSha256 sets the "sha256" field.
func (u *SupportTicketAttachmentUpsertBulk) SetSha256(v string) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateSha256() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateSha256()
	})
}

// SetHiddenAt sets the "hidden_at" field.
func (u *SupportTicketAttachmentUpsertBulk) SetHiddenAt(v time.Time) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetHiddenAt(v)
	})
}

// UpdateHiddenAt sets the "hidden_at" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateHiddenAt() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateHiddenAt()
	})
}

// ClearHiddenAt clears the value of the "hidden_at" field.
func (u *SupportTicketAttachmentUpsertBulk) ClearHiddenAt() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearHiddenAt()
	})
}

// SetHiddenBy sets the "hidden_by" field.
func (u *SupportTicketAttachmentUpsertBulk) SetHiddenBy(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetHiddenBy(v)
	})
}

// AddHiddenBy adds v to the "hidden_by" field.
func (u *SupportTicketAttachmentUpsertBulk) AddHiddenBy(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddHiddenBy(v)
	})
}

// UpdateHiddenBy sets the "hidden_by" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateHiddenBy() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateHiddenBy()
	})
}

// ClearHiddenBy clears the value of the "hidden_by" field.
func (u *SupportTicketAttachmentUpsertBulk) ClearHiddenBy() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearHiddenBy()
	})
}

// Exec executes the query.
func (u *SupportTicketAttachmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupportTicketAttachmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportTicketAttachmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportTicketAttachmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
