// Code generated by ent, DO NOT EDIT.

package supportticketread

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the supportticketread type in the database.
	Label = "support_ticket_read"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTicketID holds the string denoting the ticket_id field in the database.
	FieldTicketID = "ticket_id"
	// FieldReaderID holds the string denoting the reader_id field in the database.
	FieldReaderID = "reader_id"
	// FieldLastReadMessageID holds the string denoting the last_read_message_id field in the database.
	FieldLastReadMessageID = "last_read_message_id"
	// FieldReadAt holds the string denoting the read_at field in the database.
	FieldReadAt = "read_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the supportticketread in the database.
	Table = "support_ticket_reads"
)

// Columns holds all SQL columns for supportticketread fields.
var Columns = []string{
	FieldID,
	FieldTicketID,
	FieldReaderID,
	FieldLastReadMessageID,
	FieldReadAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReadAt holds the default value on creation for the "read_at" field.
	DefaultReadAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the SupportTicketRead queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTicketID orders the results by the ticket_id field.
func ByTicketID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketID, opts...).ToFunc()
}

// ByReaderID orders the results by the reader_id field.
func ByReaderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReaderID, opts...).ToFunc()
}

// ByLastReadMessageID orders the results by the last_read_message_id field.
func ByLastReadMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastReadMessageID, opts...).ToFunc()
}

// ByReadAt orders the results by the read_at field.
func ByReadAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReadAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
