import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount, type VueWrapper } from '@vue/test-utils'
import { reactive, ref } from 'vue'
import Select from '@/components/common/Select.vue'
import StudioImageSettings from '@/components/image/StudioImageSettings.vue'
import ConfirmDialog from '@/components/common/ConfirmDialog.vue'
import type { StudioCreation } from '@/stores/imageStudio'
import ImageStudioView from '../ImageStudioView.vue'
import messages from '@/i18n/locales/en/imageStudio'
import type { ApiKey, Group } from '@/types'

const mocks = vi.hoisted(() => ({ list: vi.fn(), create: vi.fn(), groups: vi.fn(), rates: vi.fn(), status: vi.fn(), generate: vi.fn(), resume: vi.fn(), resumePending: vi.fn(), remove: vi.fn(), file: vi.fn(), showError: vi.fn(), showSuccess: vi.fn(), creations: [] as StudioCreation[] }))
vi.mock('@/api/keys', () => ({ keysAPI: { list: mocks.list, create: mocks.create } }))
vi.mock('@/api/groups', () => ({ userGroupsAPI: { getUserGroupRates: mocks.rates } }))
vi.mock('@/api/imageStudio', async importOriginal => ({ ...await importOriginal<object>(), getImageGenerationGroups: mocks.groups, getImageStudioStatus: mocks.status, getStudioFile: mocks.file }))
vi.mock('@/stores/imageStudio', () => ({ useImageStudioStore: () => ({ creations: reactive(mocks.creations), remove: mocks.remove, get generating() { return mocks.creations.some(item => item.status === 'generating') }, historyLoading: false, historyUnavailable: false, generate: mocks.generate, resume: mocks.resume, resumePending: mocks.resumePending }) }))
vi.mock('@/stores/app', () => ({ useAppStore: () => ({ showError: mocks.showError, showSuccess: mocks.showSuccess }) }))
vi.mock('vue-i18n', async importOriginal => ({ ...await importOriginal<object>(), useI18n: () => ({
  locale: ref('en'),
  t: (key: string, params: Record<string, string | number> = {}) => {
    const text = messages.imageStudio[key.replace('imageStudio.', '') as keyof typeof messages.imageStudio] || key
    return text.replace(/\{(\w+)\}/g, (_match, name: string) => String(params[name] ?? name))
  },
}) }))

const imageGroup = { id: 1, name: 'OpenAI Images', platform: 'openai', status: 'active', allow_image_generation: true, image_models: ['gpt-image-2'], rate_multiplier: 1, image_price_1k: 0.1, image_price_2k: 0.2, image_price_4k: 0.4 } as Group
const imageKey = { id: 7, group_id: 1, name: 'Drawing key', key: 'test-key', status: 'active', quota: 0, quota_used: 0, group: imageGroup } as ApiKey
const otherGroups = [
  { ...imageGroup, id: 2, name: 'Text only', allow_image_generation: false },
  { ...imageGroup, id: 3, name: 'Grok Images', platform: 'grok' },
  { ...imageGroup, id: 4, name: 'Inactive', status: 'inactive' },
]
const render = () => mount(ImageStudioView, { global: {
  stubs: {
    teleport: true,
    AppLayout: { template: '<div><slot /></div>' },
    BaseDialog: { props: ['show'], template: '<section v-if="show" data-testid="dialog"><slot /></section>' },
    RouterLink: { template: '<a><slot /></a>' },
  },
} })

const select = (wrapper: VueWrapper, label: string) => {
  const component = wrapper.findAllComponents(Select).find(item => item.props('ariaLabel') === label)
  if (!component) throw new Error(`Select not found: ${label}`)
  return component
}
const choose = async (wrapper: VueWrapper, label: string, value: string | number) => {
  if (['Aspect ratio', 'Resolution', 'Image count'].includes(label)) {
    const component = select(wrapper, 'Ratio, resolution and count')
    if (!component.find('[role="dialog"]').exists()) await component.get('button').trigger('click')
    if (label === 'Resolution') {
      await component.get(`[role="group"][aria-label="${label}"] button[data-preset="${value}"]`).trigger('click')
      return
    }
    await component.get(`[role="group"][aria-label="${label}"] button[aria-label="${label === 'Image count' ? `${value} images` : value}"]`).trigger('click')
    return
  }
  const component = select(wrapper, label)
  const option = component.props('options').find(option => option.value === value)
  await component.get('button').trigger('click')
  const item = component.findAll('[role="option"]').find(item => item.text() === option?.label)
  if (!item) throw new Error(`Option not found: ${value}`)
  await item.trigger('click')
}

beforeEach(() => {
  vi.clearAllMocks()
  mocks.groups.mockResolvedValue([imageGroup])
  mocks.list.mockResolvedValue({ items: [imageKey], pages: 1 })
  mocks.rates.mockResolvedValue({})
  mocks.status.mockResolvedValue({ available: true })
  mocks.generate.mockReset()
  mocks.remove.mockReset()
  mocks.file.mockReset()
  mocks.creations = []
})
afterEach(() => vi.unstubAllGlobals())

describe('image studio user flow', () => {
  it('reuses valid signatures on repeated previews and cycles only the selected batch', async () => {
    const url = (index: number) => `https://images.test/${index}.png?X-Amz-Date=20990905T080000Z&X-Amz-Expires=3600`
    const batch = { id: 'batch', prompt: 'Batch prompt', model: 'gpt-image-2', ratio: '16:9', resolution: '1K', count: 3, keyId: 7, keyName: 'Drawing key', createdAt: Date.now(), status: 'completed', images: [1, 2, 3].map(index => ({ id: `image-${index}`, url: url(index) })), references: [] } as StudioCreation
    mocks.creations = [batch, { ...batch, id: 'other', images: [{ id: 'other-image', url: 'https://images.test/other.png' }] }]
    const wrapper = render(); await flushPromises()
    await wrapper.findAll('.picture-open')[2].trigger('click'); await flushPromises()
    expect(wrapper.get('.preview-position').text()).toBe('2 / 3')
    expect(wrapper.findAll('.preview-thumbnails button')).toHaveLength(3)
    await wrapper.get('[aria-label="Next image"]').trigger('click')
    expect(wrapper.get('.preview-position').text()).toBe('3 / 3')
    await wrapper.get('[aria-label="Next image"]').trigger('click')
    expect(wrapper.get('.preview-position').text()).toBe('1 / 3')
    document.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowLeft' })); await flushPromises()
    expect(wrapper.get('.preview-position').text()).toBe('3 / 3')
    await wrapper.get('[aria-label="Image 2"]').trigger('click')
    expect(wrapper.get('.preview-original').attributes('href')).toBe(url(2))
    const gallery = wrapper.findComponent({ name: 'StudioImagePreview' })
    gallery.vm.$emit('close'); await flushPromises()
    await wrapper.findAll('.picture-open')[2].trigger('click'); await flushPromises()
    expect(mocks.file).not.toHaveBeenCalled()
    expect(wrapper.get('.preview-original').attributes('href')).toBe(url(2))
    wrapper.unmount()
  })
  it('renews expired signatures and retries early failures without refreshing healthy links', async () => {
    const renewed = 'https://images.test/fresh.png?X-Amz-Date=20990905T080000Z&X-Amz-Expires=3600'
    const image = { id: 'image', url: 'https://images.test/old.png?X-Amz-Date=20200101T000000Z&X-Amz-Expires=3600' }
    mocks.creations = [{ id: 'batch', prompt: 'Prompt', model: 'gpt-image-2', ratio: '1:1', resolution: '1K', count: 1, keyId: 7, keyName: 'Drawing key', createdAt: Date.now(), status: 'completed', images: [image], references: [] }]
    mocks.file.mockResolvedValue({ id: 'image', url: renewed })
    const wrapper = render(); await flushPromises()
    await wrapper.get('.picture-open').trigger('click'); await flushPromises()
    expect(mocks.file).toHaveBeenCalledTimes(1)
    expect(wrapper.get('.preview-original').attributes('href')).toBe(renewed)
    expect(wrapper.find('.preview-arrow').exists()).toBe(false)
    mocks.file.mockResolvedValue({ id: 'image', url: 'https://blob.fastvibe.dev/images/new.png' })
    await wrapper.get('.preview-image').trigger('error'); await flushPromises()
    expect(mocks.file).toHaveBeenCalledTimes(2)
    expect(wrapper.get('.preview-original').attributes('href')).toBe('https://blob.fastvibe.dev/images/new.png')
    wrapper.unmount()
  })

  it('defaults to square without an automatic option and preserves historical automatic metadata', async () => {
    mocks.creations = [{ id: 'auto', prompt: 'Automatic composition', model: 'gpt-image-2', ratio: 'auto', resolution: '1K', count: 2, keyId: 7, keyName: 'Drawing key', createdAt: Date.now(), status: 'failed', images: [], references: [] }]
    const wrapper = render(); await flushPromises()
    await select(wrapper, 'Ratio, resolution and count').get('button').trigger('click')
    expect(wrapper.getComponent(StudioImageSettings).props('ratio')).toBe('1:1')
    expect(wrapper.get('[aria-label="Aspect ratio"] button[aria-pressed="true"]').attributes('aria-label')).toBe('1:1')
    expect(wrapper.find('[aria-label="Aspect ratio"] button[aria-label="Auto"]').exists()).toBe(false)
    expect(wrapper.get('input[aria-label="Image width"]').attributes('disabled')).toBeUndefined()
    expect((wrapper.get('input[aria-label="Image width"]').element as HTMLInputElement).value).toBe('1024')
    expect((wrapper.get('input[aria-label="Image height"]').element as HTMLInputElement).value).toBe('1024')
    await choose(wrapper, 'Image count', 3)
    expect(wrapper.getComponent(StudioImageSettings).props('count')).toBe(3)
    await wrapper.get('textarea').setValue('Square draft')
    await wrapper.get('.studio-composer').trigger('submit')
    expect(mocks.generate.mock.calls[0][3]).toBe('1:1')
    await wrapper.findAll('.creation-actions button').find(item => item.text() === 'Generate again')!.trigger('click'); await flushPromises()
    expect(mocks.generate).toHaveBeenCalledTimes(1)
    expect(wrapper.getComponent(StudioImageSettings).props('ratio')).toBe('1:1')
    expect(mocks.creations[0].ratio).toBe('auto')
    expect(wrapper.get('.creation-meta').text()).toContain('Auto')
    await choose(wrapper, 'Aspect ratio', '16:9')
    expect(wrapper.get('input[aria-label="Image width"]').attributes('disabled')).toBeUndefined()
    expect((wrapper.get('input[aria-label="Image width"]').element as HTMLInputElement).value).toBe('1792')
    expect(wrapper.getComponent(StudioImageSettings).props('resolution')).toBe('1K')
    wrapper.unmount()
  })
  it('displays history from oldest to newest without changing the paginated store order', async () => {
    mocks.creations = [3, 2, 1].map(index => ({ id: `creation-${index}`, prompt: `Creation ${index}`, model: 'gpt-image-2', ratio: '1:1', resolution: '1K', count: 1, keyId: 7, keyName: 'Drawing key', createdAt: index * 1000, status: 'failed', images: [], references: [] }))
    const wrapper = render(); await flushPromises()
    expect(wrapper.findAll('.creation-caption > p').map(item => item.text())).toEqual(['Creation 1', 'Creation 2', 'Creation 3'])
    expect(mocks.creations.map(item => item.id)).toEqual(['creation-3', 'creation-2', 'creation-1'])
    wrapper.unmount()
  })
  it('allows new drafts and regeneration while other tasks are running, without duplicate empty submits', async () => {
    mocks.creations = [{ id: 'running', prompt: 'Existing task', model: 'gpt-image-2', ratio: '1:1', resolution: '1K', count: 1, keyId: 7, keyName: 'Drawing key', createdAt: Date.now(), status: 'generating', images: [], references: [] }]
    const finishes: (() => void)[] = []
    mocks.generate.mockImplementation(() => new Promise<void>(resolve => { finishes.push(resolve) }))
    const wrapper = render(); await flushPromises()
    const input = wrapper.get('textarea')
    const button = wrapper.get('.generate-button')
    await input.setValue('Second task')
    expect(button.attributes('disabled')).toBeUndefined()
    expect(button.attributes('aria-label')).toBe('Generate')
    await wrapper.get('.studio-composer').trigger('submit')
    await wrapper.get('.studio-composer').trigger('submit')
    expect(mocks.generate).toHaveBeenCalledTimes(1)
    expect(button.attributes('disabled')).toBeDefined()
    await input.setValue('Third task')
    await input.trigger('keydown', { key: 'Enter', ctrlKey: true })
    expect(mocks.generate.mock.calls.map(call => call[1])).toEqual(['Second task', 'Third task'])
    const regenerate = wrapper.findAll('.creation-actions button').find(item => item.text() === 'Generate again')!
    expect(regenerate.attributes('disabled')).toBeUndefined()
    await regenerate.trigger('click'); await flushPromises()
    expect(mocks.generate.mock.calls.map(call => call[1])).toEqual(['Second task', 'Third task', 'Existing task'])
    await input.setValue('Next draft')
    finishes.reverse().forEach(finish => finish()); await flushPromises()
    expect((input.element as HTMLTextAreaElement).value).toBe('Next draft')
    wrapper.unmount()
  })
  it('adds a generated image to the draft using a renewed URL without replacing existing inputs', async () => {
    const generated = { id: 'output-1', url: 'https://example.test/expired.png' }
    mocks.creations = [{ id: 'creation-1', prompt: 'Original image prompt', model: 'gpt-image-2', ratio: '1:1', resolution: '1K', count: 1, keyId: 7, keyName: 'Drawing key', createdAt: Date.now(), status: 'completed', images: [generated], references: [] }]
    mocks.file.mockResolvedValue({ ...generated, url: 'https://example.test/renewed.png', size: 12, content_type: 'image/png' })
    let finish!: (response: unknown) => void
    const fetchImage = vi.fn(() => new Promise(resolve => { finish = resolve }))
    vi.stubGlobal('fetch', fetchImage)
    let blobID = 0
    vi.stubGlobal('URL', class extends URL { static createObjectURL = vi.fn(() => `blob:reference-${++blobID}`); static revokeObjectURL = vi.fn() })
    const wrapper = render()
    await flushPromises()
    const original = new File(['original'], 'original.png', { type: 'image/png' })
    const upload = wrapper.get('input[type="file"]')
    Object.defineProperty(upload.element, 'files', { value: [original] })
    await upload.trigger('change')
    await wrapper.get('textarea').setValue('My draft')
    await wrapper.get('.picture-reference').trigger('click')
    await flushPromises()
    expect(mocks.file).toHaveBeenCalledWith('output-1')
    expect(fetchImage).toHaveBeenCalledWith('https://example.test/renewed.png', expect.objectContaining({ credentials: 'omit', referrerPolicy: 'no-referrer' }))
    expect(wrapper.get('.generate-button').attributes('disabled')).toBeDefined()
    await wrapper.get('textarea').setValue('My next draft')
    finish({ ok: true, blob: async () => new Blob(['generated'], { type: 'image/png' }) })
    await flushPromises()
    expect(wrapper.findAll('.reference-thumbnail')).toHaveLength(2)
    expect((wrapper.get('textarea').element as HTMLTextAreaElement).value).toBe('My next draft')
    expect(wrapper.get('.picture-reference').attributes('disabled')).toBeDefined()
    expect(mocks.showSuccess).not.toHaveBeenCalled()
    await wrapper.get('.studio-composer').trigger('submit')
    const files = mocks.generate.mock.calls[0][6] as File[]
    expect(files[0]).toBe(original)
    expect(files[1].type).toBe('image/png')
    expect(files[1].name).toBe('image-creation-1-1.png')
    expect(mocks.generate.mock.calls[0][1]).toBe('My next draft')
    wrapper.unmount()
  })
  it('enforces the reference limit and preserves the draft when an image is too large or fails to load', async () => {
    mocks.creations = [{ id: 'creation-1', prompt: 'Original', model: 'gpt-image-2', ratio: '1:1', resolution: '1K', count: 1, keyId: 7, keyName: 'Drawing key', createdAt: Date.now(), status: 'completed', images: [{ id: 'output-1', url: 'https://example.test/image.png' }], references: [] }]
    let blobID = 0
    vi.stubGlobal('URL', class extends URL { static createObjectURL = vi.fn(() => `blob:reference-${++blobID}`); static revokeObjectURL = vi.fn() })
    const fetchImage = vi.fn().mockRejectedValue(new Error('Download failed'))
    vi.stubGlobal('fetch', fetchImage)
    const wrapper = render()
    await flushPromises()
    const upload = wrapper.get('input[type="file"]')
    Object.defineProperty(upload.element, 'files', { value: Array.from({ length: 4 }, (_, i) => new File(['original'], `${i}.png`, { type: 'image/png' })) })
    await upload.trigger('change')
    await wrapper.get('textarea').setValue('Keep my draft')
    expect(wrapper.get('.picture-reference').attributes('disabled')).toBeDefined()
    expect(mocks.file).not.toHaveBeenCalled()
    await wrapper.findAll('.reference-remove')[0].trigger('click')
    mocks.file.mockResolvedValueOnce({ size: 11 * 1024 * 1024 })
    await wrapper.get('.picture-reference').trigger('click')
    await flushPromises()
    expect(fetchImage).not.toHaveBeenCalled()
    expect(mocks.showError).toHaveBeenCalledWith(expect.stringContaining('10 MB'))
    mocks.file.mockResolvedValueOnce({ size: 12, url: 'https://example.test/renewed.png' })
    await wrapper.get('.picture-reference').trigger('click')
    await flushPromises()
    expect(mocks.showError).toHaveBeenLastCalledWith('Download failed')
    expect(wrapper.findAll('.reference-thumbnail')).toHaveLength(3)
    expect((wrapper.get('textarea').element as HTMLTextAreaElement).value).toBe('Keep my draft')
    wrapper.unmount()
  })
  it('requires global delete confirmation and retains the dialog when cleanup fails', async () => {
    mocks.creations = [{ id: 'creation-1', taskId: 'creation-1', prompt: 'My saved image', model: 'gpt-image-2', ratio: '1:1', resolution: '1K', count: 1, keyId: 7, keyName: 'Drawing key', createdAt: Date.now(), status: 'completed', images: [{ id: 'image-1', url: 'https://example.test/image.png' }], references: [] }]
    const wrapper = render()
    await flushPromises()
    await wrapper.get('.delete-creation').trigger('click')
    const confirmation = wrapper.getComponent(ConfirmDialog)
    expect(confirmation.props('show')).toBe(true)
    expect(confirmation.props('danger')).toBe(true)
    expect(confirmation.props('message')).toContain('reference images')
    expect(mocks.remove).not.toHaveBeenCalled()
    confirmation.vm.$emit('cancel')
    await flushPromises()
    expect(confirmation.props('show')).toBe(false)
    expect(mocks.remove).not.toHaveBeenCalled()
    await wrapper.get('.delete-creation').trigger('click')
    let fail!: (error: Error) => void
    mocks.remove.mockImplementationOnce(() => new Promise((_resolve, reject) => { fail = reject }))
    confirmation.vm.$emit('confirm')
    confirmation.vm.$emit('confirm')
    await flushPromises()
    expect(mocks.remove).toHaveBeenCalledTimes(1)
    expect(confirmation.props('loading')).toBe(true)
    fail(new Error('Object storage unavailable'))
    await flushPromises()
    expect(confirmation.props('show')).toBe(true)
    expect(confirmation.props('loading')).toBe(false)
    expect(confirmation.text()).toContain('Object storage unavailable')
    mocks.remove.mockResolvedValueOnce(undefined)
    confirmation.vm.$emit('confirm')
    await flushPromises()
    expect(mocks.remove).toHaveBeenLastCalledWith('creation-1')
    expect(confirmation.props('show')).toBe(false)
    wrapper.unmount()
  })
  it('filters keys, including keys on later pages, without opening creation for existing keys', async () => {
    mocks.list.mockResolvedValueOnce({ items: [{ ...imageKey, id: 8, group_id: 2, group: otherGroups[0] }], pages: 2 }).mockResolvedValueOnce({ items: [imageKey], pages: 2 })
    const wrapper = render()
    await flushPromises()
    expect(mocks.list).toHaveBeenCalledTimes(2)
    await wrapper.get('button[aria-label="Image Key"]').trigger('click')
    expect(wrapper.findAll('[role="option"]')).toHaveLength(2)
    expect(wrapper.getComponent(Select).props('options').map(option => option.label)).toEqual(['Drawing key · OpenAI Images', 'Create image Key'])
    expect(wrapper.find('[data-testid="dialog"]').exists()).toBe(false)
    wrapper.unmount()
  })
  it('opens creation only from the Key dropdown and selects the created image Key', async () => {
    mocks.list.mockResolvedValue({ items: [], pages: 0 })
    mocks.create.mockResolvedValue(imageKey)
    const wrapper = render()
    await flushPromises()
    expect(wrapper.find('[data-testid="dialog"]').exists()).toBe(false)
    await wrapper.get('button[aria-label="Image Key"]').trigger('click')
    expect(wrapper.findAll('[role="option"]')).toHaveLength(1)
    await wrapper.get('[role="option"]').trigger('click')
    expect(wrapper.find('[data-testid="dialog"]').exists()).toBe(true)
    const groupSelect = select(wrapper, 'Image group')
    expect(groupSelect.text()).toContain('OpenAI Images')
    expect(JSON.stringify(groupSelect.props('options'))).not.toMatch(/Text only|Grok Images|Inactive/)
    await wrapper.get('input[aria-label="Key name"]').setValue('My art')
    await wrapper.get('.create-key-form').trigger('submit')
    await flushPromises()
    expect(mocks.create).toHaveBeenCalledWith('My art', 1)
    expect(wrapper.find('[data-testid="dialog"]').exists()).toBe(false)
    expect(wrapper.get('button[aria-label="Image Key"]').text()).toContain('Drawing key')
    expect(select(wrapper, 'Model').props('modelValue')).toBe('gpt-image-2')
    wrapper.unmount()
  })
  it('does not submit without an eligible group or a usable model', async () => {
    mocks.groups.mockResolvedValue([])
    mocks.list.mockResolvedValue({ items: [], pages: 0 })
    const wrapper = render()
    await flushPromises()
    await wrapper.get('button[aria-label="Image Key"]').trigger('click')
    await wrapper.get('[role="option"]').trigger('click')
    expect(wrapper.get('.create-key-form button[type="submit"]').attributes('disabled')).toBeDefined()
    await wrapper.get('textarea').setValue('A landscape')
    await wrapper.get('.studio-composer').trigger('submit')
    expect(mocks.generate).not.toHaveBeenCalled()
    expect((wrapper.get('textarea').element as HTMLTextAreaElement).value).toBe('A landscape')
    wrapper.unmount()
  })
  it('excludes a text-only Key even when its embedded group allows image generation', async () => {
    const textKey = { ...imageKey, id: 9, name: 'test', group_id: 9, group: { ...imageGroup, id: 9, name: 'gpr-pro' } }
    mocks.list.mockResolvedValue({ items: [textKey, imageKey], pages: 1 })
    const wrapper = render()
    await flushPromises()
    expect(wrapper.getComponent(Select).props('options').map(option => option.value)).toEqual([7, 'create'])
    expect(wrapper.get('button[aria-label="Image Key"]').text()).toContain('Drawing key')
    expect(wrapper.text()).not.toContain('gpr-pro')
    expect(wrapper.find('.model-error').exists()).toBe(false)
    wrapper.unmount()
  })
  it('leaves only the create action when all existing Keys belong to text-only groups', async () => {
    mocks.groups.mockResolvedValue([])
    const wrapper = render()
    await flushPromises()
    expect(wrapper.getComponent(Select).props('options').map(option => option.value)).toEqual(['create'])
    expect(wrapper.find('[data-testid="dialog"]').exists()).toBe(false)
    expect(wrapper.find('.model-error').exists()).toBe(false)
    wrapper.unmount()
  })
  it('submits chosen parameters once and rejects invalid reference files', async () => {
    const wrapper = render()
    await flushPromises()
    await wrapper.get('textarea').setValue('A glass greenhouse')
    await choose(wrapper, 'Aspect ratio', '3:2')
    await choose(wrapper, 'Resolution', '2K')
    expect(wrapper.get('.price-info').text()).toBe('$0.2 / image')
    await choose(wrapper, 'Image count', 4)
    expect(wrapper.get('.price-info').text()).toBe('$0.2 / image')
    await wrapper.get('.studio-composer').trigger('submit')
    expect(mocks.generate).toHaveBeenCalledWith('test-key', 'A glass greenhouse', 'gpt-image-2', '3:2', 4, '2K', [], 7, 'Drawing key')
    const input = wrapper.get('input[type="file"]')
    Object.defineProperty(input.element, 'files', { value: [new File(['oops'], 'bad.svg', { type: 'image/svg+xml' })] })
    await input.trigger('change')
    expect(wrapper.get('.form-error').text()).toContain('PNG, JPEG or WebP')
    wrapper.unmount()
  })
  it('clears the submitted prompt and references immediately, preserving the request and next draft', async () => {
    const createURL = vi.fn().mockReturnValue('blob:reference')
    const revokeURL = vi.fn()
    vi.stubGlobal('URL', class extends URL {
      static createObjectURL = createURL
      static revokeObjectURL = revokeURL
    })
    let finish!: () => void
    mocks.generate.mockImplementation(() => new Promise<void>(resolve => { finish = resolve }))
    const wrapper = render()
    await flushPromises()
    const reference = new File(['reference bytes'], 'reference.png', { type: 'image/png' })
    const input = wrapper.get('input[type="file"]')
    Object.defineProperty(input.element, 'files', { value: [reference], configurable: true })
    await input.trigger('change')
    await wrapper.get('textarea').setValue('Turn this into a painting')
    await wrapper.get('.studio-composer').trigger('submit')
    expect(mocks.generate.mock.calls[0][1]).toBe('Turn this into a painting')
    expect(mocks.generate.mock.calls[0][6]).toEqual([reference])
    expect(reference.size).toBeGreaterThan(0)
    expect((wrapper.get('textarea').element as HTMLTextAreaElement).value).toBe('')
    expect(wrapper.find('.reference-thumbnail').exists()).toBe(false)
    expect(revokeURL).toHaveBeenCalledWith('blob:reference')
    await wrapper.get('textarea').setValue('My next idea')
    Object.defineProperty(input.element, 'files', { value: [reference], configurable: true })
    await input.trigger('change')
    finish()
    await flushPromises()
    expect((wrapper.get('textarea').element as HTMLTextAreaElement).value).toBe('My next idea')
    expect(wrapper.find('.reference-thumbnail').exists()).toBe(true)
    wrapper.unmount()
  })
  it('offers common ratios and keeps resolution and model switches valid', async () => {
    mocks.groups.mockResolvedValue([{ ...imageGroup, image_models: ['gpt-image-2', 'gpt-image-1.5'] }])
    const wrapper = render()
    await flushPromises()
    const settings = wrapper.getComponent(StudioImageSettings)
    await select(wrapper, 'Ratio, resolution and count').get('button').trigger('click')
    const options = (label: string) => settings.findAll(`[role="group"][aria-label="${label}"] button`).map(item => item.attributes('aria-label'))
    expect(options('Aspect ratio')).toEqual(['1:1', '3:4', '16:9', '4:3', '9:16', '2:3', '3:2', '21:9'])
    expect(settings.props('resolution')).toBe('1K')
    await choose(wrapper, 'Aspect ratio', '16:9')
    expect(options('Resolution')).toEqual(['1K', '2K', '4K'])
    expect(settings.props('resolution')).toBe('1K')
    await wrapper.get('textarea').setValue('A wide landscape')
    await wrapper.get('.studio-composer').trigger('submit')
    expect(mocks.generate).toHaveBeenCalledWith('test-key', 'A wide landscape', 'gpt-image-2', '16:9', 1, '1K', [], 7, 'Drawing key')
    await choose(wrapper, 'Model', 'gpt-image-1.5')
    expect(options('Aspect ratio')).toEqual(['1:1', '2:3', '3:2'])
    expect(settings.props('ratio')).toBe('1:1')
    expect(settings.props('resolution')).toBe('1K')
    expect(settings.get('input[aria-label="Image width"]').attributes('readonly')).toBeDefined()
    wrapper.unmount()
  })
  it('links dimensions, validates before spending and submits the exact custom size', async () => {
    const wrapper = render(); await flushPromises()
    await wrapper.get('textarea').setValue('A panoramic landscape')
    await choose(wrapper, 'Aspect ratio', '21:9')
    const width = wrapper.get('input[aria-label="Image width"]')
    await width.setValue('100'); await width.trigger('blur')
    await wrapper.get('.studio-composer').trigger('submit')
    expect(mocks.generate).not.toHaveBeenCalled()
    expect(wrapper.find('.size-error').exists()).toBe(true)
    const correctedWidth = wrapper.get('input[aria-label="Image width"]')
    await correctedWidth.setValue('3025'); await correctedWidth.trigger('blur'); await flushPromises()
    expect(wrapper.getComponent(StudioImageSettings).props('size')).toBe('3024x1296')
    expect((wrapper.get('input[aria-label="Image width"]').element as HTMLInputElement).value).toBe('3024')
    expect((wrapper.get('input[aria-label="Image height"]').element as HTMLInputElement).value).toBe('1296')
    expect(wrapper.getComponent(StudioImageSettings).props('resolution')).toBe('4K')
    expect(wrapper.get('.price-info').text()).toBe('$0.4 / image')
    await wrapper.get('.studio-composer').trigger('submit')
    expect(mocks.generate).toHaveBeenCalledWith('test-key', 'A panoramic landscape', 'gpt-image-2', '21:9', 1, '4K', [], 7, 'Drawing key', '3024x1296')
    await choose(wrapper, 'Resolution', '2K')
    expect((wrapper.get('input[aria-label="Image width"]').element as HTMLInputElement).value).toBe('2016')
    expect(wrapper.getComponent(StudioImageSettings).props('size')).toBeUndefined()
    wrapper.unmount()
  })
  it('restores saved custom dimensions when regenerating a historical image', async () => {
    mocks.creations = [{ id: 'custom', prompt: 'Original panorama', model: 'gpt-image-2', ratio: '21:9', resolution: '4K', size: '3024x1296', count: 2, keyId: 7, keyName: 'Drawing key', createdAt: Date.now(), status: 'failed', images: [], references: [] }]
    const wrapper = render(); await flushPromises()
    expect(wrapper.get('.creation-meta [title="3024×1296"]').text()).toBe('4K')
    await wrapper.findAll('.creation-actions button').find(item => item.text() === 'Generate again')!.trigger('click')
    await flushPromises()
    expect(mocks.generate).toHaveBeenCalledWith('test-key', 'Original panorama', 'gpt-image-2', '21:9', 2, '4K', [], 7, 'Drawing key', '3024x1296')
    expect(wrapper.get('.settings-summary [title="3024×1296"]').text()).toBe('4K')
    await select(wrapper, 'Ratio, resolution and count').get('button').trigger('click')
    expect(wrapper.findAll('[role="group"][aria-label="Resolution"] button[aria-pressed="true"]')).toHaveLength(0)
    wrapper.unmount()
  })
  it('shows familiar resolution labels while preserving exact preset dimensions', async () => {
    const wrapper = render(); await flushPromises()
    await choose(wrapper, 'Resolution', '4K')
    expect(wrapper.findAll('[role="group"][aria-label="Resolution"] button').map(item => item.text())).toEqual(['1K', '2K', '4K'])
    expect(wrapper.get('.settings-summary [title="2880×2880"]').text()).toBe('4K')
    expect((wrapper.get('input[aria-label="Image width"]').element as HTMLInputElement).value).toBe('2880')
    expect((wrapper.get('input[aria-label="Image height"]').element as HTMLInputElement).value).toBe('2880')
    await wrapper.get('textarea').setValue('A square poster')
    expect(wrapper.get('.price-info').text()).toBe('$0.4 / image')
    await wrapper.get('.studio-composer').trigger('submit')
    expect(mocks.generate.mock.calls[0].slice(3, 6)).toEqual(['1:1', 1, '4K'])
    wrapper.unmount()
  })
  it('blocks generation before spending when image storage is not enabled', async () => {
    mocks.status.mockResolvedValue({ available: false })
    const wrapper = render()
    await flushPromises()
    await wrapper.get('textarea').setValue('An image')
    await wrapper.get('.studio-composer').trigger('submit')
    expect(mocks.generate).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('Image storage is not enabled')
    expect((wrapper.get('textarea').element as HTMLTextAreaElement).value).toBe('An image')
    wrapper.unmount()
  })
  it('shows access errors without suggesting that failed key loading means no keys exist', async () => {
    mocks.list.mockRejectedValue(new Error('network unavailable'))
    const wrapper = render()
    await flushPromises()
    expect(wrapper.text()).toContain('network unavailable')
    expect(wrapper.getComponent(Select).props('options')).toEqual([expect.objectContaining({ value: 'create', disabled: true })])
    expect(wrapper.find('[data-testid="dialog"]').exists()).toBe(false)
    wrapper.unmount()
  })
})
