// Code generated by ent, DO NOT EDIT.

package apikeyrouteconfigoutbox

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the apikeyrouteconfigoutbox type in the database.
	Label = "api_key_route_config_outbox"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventKey holds the string denoting the event_key field in the database.
	FieldEventKey = "event_key"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldRouteVersion holds the string denoting the route_version field in the database.
	FieldRouteVersion = "route_version"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldAvailableAt holds the string denoting the available_at field in the database.
	FieldAvailableAt = "available_at"
	// FieldClaimedAt holds the string denoting the claimed_at field in the database.
	FieldClaimedAt = "claimed_at"
	// FieldClaimedBy holds the string denoting the claimed_by field in the database.
	FieldClaimedBy = "claimed_by"
	// FieldDeliveredAt holds the string denoting the delivered_at field in the database.
	FieldDeliveredAt = "delivered_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAPIKey holds the string denoting the api_key edge name in mutations.
	EdgeAPIKey = "api_key"
	// Table holds the table name of the apikeyrouteconfigoutbox in the database.
	Table = "api_key_route_config_outbox"
	// APIKeyTable is the table that holds the api_key relation/edge.
	APIKeyTable = "api_key_route_config_outbox"
	// APIKeyInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeyInverseTable = "api_keys"
	// APIKeyColumn is the table column denoting the api_key relation/edge.
	APIKeyColumn = "api_key_id"
)

// Columns holds all SQL columns for apikeyrouteconfigoutbox fields.
var Columns = []string{
	FieldID,
	FieldEventKey,
	FieldAPIKeyID,
	FieldRouteVersion,
	FieldEventType,
	FieldPayload,
	FieldAttempts,
	FieldAvailableAt,
	FieldClaimedAt,
	FieldClaimedBy,
	FieldDeliveredAt,
	FieldLastError,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventKeyValidator is a validator for the "event_key" field. It is called by the builders before save.
	EventKeyValidator func(string) error
	// RouteVersionValidator is a validator for the "route_version" field. It is called by the builders before save.
	RouteVersionValidator func(int64) error
	// DefaultEventType holds the default value on creation for the "event_type" field.
	DefaultEventType string
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
	// AttemptsValidator is a validator for the "attempts" field. It is called by the builders before save.
	AttemptsValidator func(int) error
	// DefaultAvailableAt holds the default value on creation for the "available_at" field.
	DefaultAvailableAt func() time.Time
	// ClaimedByValidator is a validator for the "claimed_by" field. It is called by the builders before save.
	ClaimedByValidator func(string) error
	// LastErrorValidator is a validator for the "last_error" field. It is called by the builders before save.
	LastErrorValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the APIKeyRouteConfigOutbox queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventKey orders the results by the event_key field.
func ByEventKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventKey, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByRouteVersion orders the results by the route_version field.
func ByRouteVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRouteVersion, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByAvailableAt orders the results by the available_at field.
func ByAvailableAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableAt, opts...).ToFunc()
}

// ByClaimedAt orders the results by the claimed_at field.
func ByClaimedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimedAt, opts...).ToFunc()
}

// ByClaimedBy orders the results by the claimed_by field.
func ByClaimedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimedBy, opts...).ToFunc()
}

// ByDeliveredAt orders the results by the delivered_at field.
func ByDeliveredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveredAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAPIKeyField orders the results by api_key field.
func ByAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}
func newAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
	)
}
