// Code generated by ent, DO NOT EDIT.

package routingartifactversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldID, id))
}

// ArtifactKind applies equality check predicate on the "artifact_kind" field. It's identical to ArtifactKindEQ.
func ArtifactKind(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldArtifactKind, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldVersion, v))
}

// ParentVersion applies equality check predicate on the "parent_version" field. It's identical to ParentVersionEQ.
func ParentVersion(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldParentVersion, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldPlatform, v))
}

// ModelFamily applies equality check predicate on the "model_family" field. It's identical to ModelFamilyEQ.
func ModelFamily(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldModelFamily, v))
}

// EndpointKind applies equality check predicate on the "endpoint_kind" field. It's identical to EndpointKindEQ.
func EndpointKind(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldEndpointKind, v))
}

// Preference applies equality check predicate on the "preference" field. It's identical to PreferenceEQ.
func Preference(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldPreference, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldStatus, v))
}

// SchemaVersion applies equality check predicate on the "schema_version" field. It's identical to SchemaVersionEQ.
func SchemaVersion(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldSchemaVersion, v))
}

// Checksum applies equality check predicate on the "checksum" field. It's identical to ChecksumEQ.
func Checksum(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldChecksum, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldCreatedBy, v))
}

// ActivatedAt applies equality check predicate on the "activated_at" field. It's identical to ActivatedAtEQ.
func ActivatedAt(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldActivatedAt, v))
}

// RetiredAt applies equality check predicate on the "retired_at" field. It's identical to RetiredAtEQ.
func RetiredAt(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldRetiredAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// ArtifactKindEQ applies the EQ predicate on the "artifact_kind" field.
func ArtifactKindEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldArtifactKind, v))
}

// ArtifactKindNEQ applies the NEQ predicate on the "artifact_kind" field.
func ArtifactKindNEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldArtifactKind, v))
}

// ArtifactKindIn applies the In predicate on the "artifact_kind" field.
func ArtifactKindIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldArtifactKind, vs...))
}

// ArtifactKindNotIn applies the NotIn predicate on the "artifact_kind" field.
func ArtifactKindNotIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldArtifactKind, vs...))
}

// ArtifactKindGT applies the GT predicate on the "artifact_kind" field.
func ArtifactKindGT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldArtifactKind, v))
}

// ArtifactKindGTE applies the GTE predicate on the "artifact_kind" field.
func ArtifactKindGTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldArtifactKind, v))
}

// ArtifactKindLT applies the LT predicate on the "artifact_kind" field.
func ArtifactKindLT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldArtifactKind, v))
}

// ArtifactKindLTE applies the LTE predicate on the "artifact_kind" field.
func ArtifactKindLTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldArtifactKind, v))
}

// ArtifactKindContains applies the Contains predicate on the "artifact_kind" field.
func ArtifactKindContains(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContains(FieldArtifactKind, v))
}

// ArtifactKindHasPrefix applies the HasPrefix predicate on the "artifact_kind" field.
func ArtifactKindHasPrefix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasPrefix(FieldArtifactKind, v))
}

// ArtifactKindHasSuffix applies the HasSuffix predicate on the "artifact_kind" field.
func ArtifactKindHasSuffix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasSuffix(FieldArtifactKind, v))
}

// ArtifactKindEqualFold applies the EqualFold predicate on the "artifact_kind" field.
func ArtifactKindEqualFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEqualFold(FieldArtifactKind, v))
}

// ArtifactKindContainsFold applies the ContainsFold predicate on the "artifact_kind" field.
func ArtifactKindContainsFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContainsFold(FieldArtifactKind, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContainsFold(FieldVersion, v))
}

// ParentVersionEQ applies the EQ predicate on the "parent_version" field.
func ParentVersionEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldParentVersion, v))
}

// ParentVersionNEQ applies the NEQ predicate on the "parent_version" field.
func ParentVersionNEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldParentVersion, v))
}

// ParentVersionIn applies the In predicate on the "parent_version" field.
func ParentVersionIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldParentVersion, vs...))
}

// ParentVersionNotIn applies the NotIn predicate on the "parent_version" field.
func ParentVersionNotIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldParentVersion, vs...))
}

// ParentVersionGT applies the GT predicate on the "parent_version" field.
func ParentVersionGT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldParentVersion, v))
}

// ParentVersionGTE applies the GTE predicate on the "parent_version" field.
func ParentVersionGTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldParentVersion, v))
}

// ParentVersionLT applies the LT predicate on the "parent_version" field.
func ParentVersionLT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldParentVersion, v))
}

// ParentVersionLTE applies the LTE predicate on the "parent_version" field.
func ParentVersionLTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldParentVersion, v))
}

// ParentVersionContains applies the Contains predicate on the "parent_version" field.
func ParentVersionContains(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContains(FieldParentVersion, v))
}

// ParentVersionHasPrefix applies the HasPrefix predicate on the "parent_version" field.
func ParentVersionHasPrefix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasPrefix(FieldParentVersion, v))
}

// ParentVersionHasSuffix applies the HasSuffix predicate on the "parent_version" field.
func ParentVersionHasSuffix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasSuffix(FieldParentVersion, v))
}

// ParentVersionIsNil applies the IsNil predicate on the "parent_version" field.
func ParentVersionIsNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIsNull(FieldParentVersion))
}

// ParentVersionNotNil applies the NotNil predicate on the "parent_version" field.
func ParentVersionNotNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotNull(FieldParentVersion))
}

// ParentVersionEqualFold applies the EqualFold predicate on the "parent_version" field.
func ParentVersionEqualFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEqualFold(FieldParentVersion, v))
}

// ParentVersionContainsFold applies the ContainsFold predicate on the "parent_version" field.
func ParentVersionContainsFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContainsFold(FieldParentVersion, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContainsFold(FieldPlatform, v))
}

// ModelFamilyEQ applies the EQ predicate on the "model_family" field.
func ModelFamilyEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldModelFamily, v))
}

// ModelFamilyNEQ applies the NEQ predicate on the "model_family" field.
func ModelFamilyNEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldModelFamily, v))
}

// ModelFamilyIn applies the In predicate on the "model_family" field.
func ModelFamilyIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldModelFamily, vs...))
}

// ModelFamilyNotIn applies the NotIn predicate on the "model_family" field.
func ModelFamilyNotIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldModelFamily, vs...))
}

// ModelFamilyGT applies the GT predicate on the "model_family" field.
func ModelFamilyGT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldModelFamily, v))
}

// ModelFamilyGTE applies the GTE predicate on the "model_family" field.
func ModelFamilyGTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldModelFamily, v))
}

// ModelFamilyLT applies the LT predicate on the "model_family" field.
func ModelFamilyLT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldModelFamily, v))
}

// ModelFamilyLTE applies the LTE predicate on the "model_family" field.
func ModelFamilyLTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldModelFamily, v))
}

// ModelFamilyContains applies the Contains predicate on the "model_family" field.
func ModelFamilyContains(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContains(FieldModelFamily, v))
}

// ModelFamilyHasPrefix applies the HasPrefix predicate on the "model_family" field.
func ModelFamilyHasPrefix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasPrefix(FieldModelFamily, v))
}

// ModelFamilyHasSuffix applies the HasSuffix predicate on the "model_family" field.
func ModelFamilyHasSuffix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasSuffix(FieldModelFamily, v))
}

// ModelFamilyEqualFold applies the EqualFold predicate on the "model_family" field.
func ModelFamilyEqualFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEqualFold(FieldModelFamily, v))
}

// ModelFamilyContainsFold applies the ContainsFold predicate on the "model_family" field.
func ModelFamilyContainsFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContainsFold(FieldModelFamily, v))
}

// EndpointKindEQ applies the EQ predicate on the "endpoint_kind" field.
func EndpointKindEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldEndpointKind, v))
}

// EndpointKindNEQ applies the NEQ predicate on the "endpoint_kind" field.
func EndpointKindNEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldEndpointKind, v))
}

// EndpointKindIn applies the In predicate on the "endpoint_kind" field.
func EndpointKindIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldEndpointKind, vs...))
}

// EndpointKindNotIn applies the NotIn predicate on the "endpoint_kind" field.
func EndpointKindNotIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldEndpointKind, vs...))
}

// EndpointKindGT applies the GT predicate on the "endpoint_kind" field.
func EndpointKindGT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldEndpointKind, v))
}

// EndpointKindGTE applies the GTE predicate on the "endpoint_kind" field.
func EndpointKindGTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldEndpointKind, v))
}

// EndpointKindLT applies the LT predicate on the "endpoint_kind" field.
func EndpointKindLT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldEndpointKind, v))
}

// EndpointKindLTE applies the LTE predicate on the "endpoint_kind" field.
func EndpointKindLTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldEndpointKind, v))
}

// EndpointKindContains applies the Contains predicate on the "endpoint_kind" field.
func EndpointKindContains(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContains(FieldEndpointKind, v))
}

// EndpointKindHasPrefix applies the HasPrefix predicate on the "endpoint_kind" field.
func EndpointKindHasPrefix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasPrefix(FieldEndpointKind, v))
}

// EndpointKindHasSuffix applies the HasSuffix predicate on the "endpoint_kind" field.
func EndpointKindHasSuffix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasSuffix(FieldEndpointKind, v))
}

// EndpointKindEqualFold applies the EqualFold predicate on the "endpoint_kind" field.
func EndpointKindEqualFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEqualFold(FieldEndpointKind, v))
}

// EndpointKindContainsFold applies the ContainsFold predicate on the "endpoint_kind" field.
func EndpointKindContainsFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContainsFold(FieldEndpointKind, v))
}

// PreferenceEQ applies the EQ predicate on the "preference" field.
func PreferenceEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldPreference, v))
}

// PreferenceNEQ applies the NEQ predicate on the "preference" field.
func PreferenceNEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldPreference, v))
}

// PreferenceIn applies the In predicate on the "preference" field.
func PreferenceIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldPreference, vs...))
}

// PreferenceNotIn applies the NotIn predicate on the "preference" field.
func PreferenceNotIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldPreference, vs...))
}

// PreferenceGT applies the GT predicate on the "preference" field.
func PreferenceGT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldPreference, v))
}

// PreferenceGTE applies the GTE predicate on the "preference" field.
func PreferenceGTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldPreference, v))
}

// PreferenceLT applies the LT predicate on the "preference" field.
func PreferenceLT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldPreference, v))
}

// PreferenceLTE applies the LTE predicate on the "preference" field.
func PreferenceLTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldPreference, v))
}

// PreferenceContains applies the Contains predicate on the "preference" field.
func PreferenceContains(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContains(FieldPreference, v))
}

// PreferenceHasPrefix applies the HasPrefix predicate on the "preference" field.
func PreferenceHasPrefix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasPrefix(FieldPreference, v))
}

// PreferenceHasSuffix applies the HasSuffix predicate on the "preference" field.
func PreferenceHasSuffix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasSuffix(FieldPreference, v))
}

// PreferenceIsNil applies the IsNil predicate on the "preference" field.
func PreferenceIsNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIsNull(FieldPreference))
}

// PreferenceNotNil applies the NotNil predicate on the "preference" field.
func PreferenceNotNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotNull(FieldPreference))
}

// PreferenceEqualFold applies the EqualFold predicate on the "preference" field.
func PreferenceEqualFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEqualFold(FieldPreference, v))
}

// PreferenceContainsFold applies the ContainsFold predicate on the "preference" field.
func PreferenceContainsFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContainsFold(FieldPreference, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContainsFold(FieldStatus, v))
}

// SchemaVersionEQ applies the EQ predicate on the "schema_version" field.
func SchemaVersionEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldSchemaVersion, v))
}

// SchemaVersionNEQ applies the NEQ predicate on the "schema_version" field.
func SchemaVersionNEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldSchemaVersion, v))
}

// SchemaVersionIn applies the In predicate on the "schema_version" field.
func SchemaVersionIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldSchemaVersion, vs...))
}

// SchemaVersionNotIn applies the NotIn predicate on the "schema_version" field.
func SchemaVersionNotIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldSchemaVersion, vs...))
}

// SchemaVersionGT applies the GT predicate on the "schema_version" field.
func SchemaVersionGT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldSchemaVersion, v))
}

// SchemaVersionGTE applies the GTE predicate on the "schema_version" field.
func SchemaVersionGTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldSchemaVersion, v))
}

// SchemaVersionLT applies the LT predicate on the "schema_version" field.
func SchemaVersionLT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldSchemaVersion, v))
}

// SchemaVersionLTE applies the LTE predicate on the "schema_version" field.
func SchemaVersionLTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldSchemaVersion, v))
}

// SchemaVersionContains applies the Contains predicate on the "schema_version" field.
func SchemaVersionContains(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContains(FieldSchemaVersion, v))
}

// SchemaVersionHasPrefix applies the HasPrefix predicate on the "schema_version" field.
func SchemaVersionHasPrefix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasPrefix(FieldSchemaVersion, v))
}

// SchemaVersionHasSuffix applies the HasSuffix predicate on the "schema_version" field.
func SchemaVersionHasSuffix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasSuffix(FieldSchemaVersion, v))
}

// SchemaVersionEqualFold applies the EqualFold predicate on the "schema_version" field.
func SchemaVersionEqualFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEqualFold(FieldSchemaVersion, v))
}

// SchemaVersionContainsFold applies the ContainsFold predicate on the "schema_version" field.
func SchemaVersionContainsFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContainsFold(FieldSchemaVersion, v))
}

// ChecksumEQ applies the EQ predicate on the "checksum" field.
func ChecksumEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldChecksum, v))
}

// ChecksumNEQ applies the NEQ predicate on the "checksum" field.
func ChecksumNEQ(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldChecksum, v))
}

// ChecksumIn applies the In predicate on the "checksum" field.
func ChecksumIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldChecksum, vs...))
}

// ChecksumNotIn applies the NotIn predicate on the "checksum" field.
func ChecksumNotIn(vs ...string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldChecksum, vs...))
}

// ChecksumGT applies the GT predicate on the "checksum" field.
func ChecksumGT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldChecksum, v))
}

// ChecksumGTE applies the GTE predicate on the "checksum" field.
func ChecksumGTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldChecksum, v))
}

// ChecksumLT applies the LT predicate on the "checksum" field.
func ChecksumLT(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldChecksum, v))
}

// ChecksumLTE applies the LTE predicate on the "checksum" field.
func ChecksumLTE(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldChecksum, v))
}

// ChecksumContains applies the Contains predicate on the "checksum" field.
func ChecksumContains(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContains(FieldChecksum, v))
}

// ChecksumHasPrefix applies the HasPrefix predicate on the "checksum" field.
func ChecksumHasPrefix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasPrefix(FieldChecksum, v))
}

// ChecksumHasSuffix applies the HasSuffix predicate on the "checksum" field.
func ChecksumHasSuffix(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldHasSuffix(FieldChecksum, v))
}

// ChecksumEqualFold applies the EqualFold predicate on the "checksum" field.
func ChecksumEqualFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEqualFold(FieldChecksum, v))
}

// ChecksumContainsFold applies the ContainsFold predicate on the "checksum" field.
func ChecksumContainsFold(v string) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldContainsFold(FieldChecksum, v))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotNull(FieldPayload))
}

// DependenciesIsNil applies the IsNil predicate on the "dependencies" field.
func DependenciesIsNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIsNull(FieldDependencies))
}

// DependenciesNotNil applies the NotNil predicate on the "dependencies" field.
func DependenciesNotNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotNull(FieldDependencies))
}

// LineageIsNil applies the IsNil predicate on the "lineage" field.
func LineageIsNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIsNull(FieldLineage))
}

// LineageNotNil applies the NotNil predicate on the "lineage" field.
func LineageNotNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotNull(FieldLineage))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotNull(FieldCreatedBy))
}

// ActivatedAtEQ applies the EQ predicate on the "activated_at" field.
func ActivatedAtEQ(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldActivatedAt, v))
}

// ActivatedAtNEQ applies the NEQ predicate on the "activated_at" field.
func ActivatedAtNEQ(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldActivatedAt, v))
}

// ActivatedAtIn applies the In predicate on the "activated_at" field.
func ActivatedAtIn(vs ...time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldActivatedAt, vs...))
}

// ActivatedAtNotIn applies the NotIn predicate on the "activated_at" field.
func ActivatedAtNotIn(vs ...time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldActivatedAt, vs...))
}

// ActivatedAtGT applies the GT predicate on the "activated_at" field.
func ActivatedAtGT(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldActivatedAt, v))
}

// ActivatedAtGTE applies the GTE predicate on the "activated_at" field.
func ActivatedAtGTE(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldActivatedAt, v))
}

// ActivatedAtLT applies the LT predicate on the "activated_at" field.
func ActivatedAtLT(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldActivatedAt, v))
}

// ActivatedAtLTE applies the LTE predicate on the "activated_at" field.
func ActivatedAtLTE(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldActivatedAt, v))
}

// ActivatedAtIsNil applies the IsNil predicate on the "activated_at" field.
func ActivatedAtIsNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIsNull(FieldActivatedAt))
}

// ActivatedAtNotNil applies the NotNil predicate on the "activated_at" field.
func ActivatedAtNotNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotNull(FieldActivatedAt))
}

// RetiredAtEQ applies the EQ predicate on the "retired_at" field.
func RetiredAtEQ(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldRetiredAt, v))
}

// RetiredAtNEQ applies the NEQ predicate on the "retired_at" field.
func RetiredAtNEQ(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldRetiredAt, v))
}

// RetiredAtIn applies the In predicate on the "retired_at" field.
func RetiredAtIn(vs ...time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldRetiredAt, vs...))
}

// RetiredAtNotIn applies the NotIn predicate on the "retired_at" field.
func RetiredAtNotIn(vs ...time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldRetiredAt, vs...))
}

// RetiredAtGT applies the GT predicate on the "retired_at" field.
func RetiredAtGT(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldRetiredAt, v))
}

// RetiredAtGTE applies the GTE predicate on the "retired_at" field.
func RetiredAtGTE(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldRetiredAt, v))
}

// RetiredAtLT applies the LT predicate on the "retired_at" field.
func RetiredAtLT(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldRetiredAt, v))
}

// RetiredAtLTE applies the LTE predicate on the "retired_at" field.
func RetiredAtLTE(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldRetiredAt, v))
}

// RetiredAtIsNil applies the IsNil predicate on the "retired_at" field.
func RetiredAtIsNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIsNull(FieldRetiredAt))
}

// RetiredAtNotNil applies the NotNil predicate on the "retired_at" field.
func RetiredAtNotNil() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotNull(FieldRetiredAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoutingArtifactVersion) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoutingArtifactVersion) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoutingArtifactVersion) predicate.RoutingArtifactVersion {
	return predicate.RoutingArtifactVersion(sql.NotPredicates(p))
}
