#!/usr/bin/env bash
set -Eeuo pipefail

# Start PostgreSQL/Redis in Docker and run the Go API + Vite dev server locally.
# The script is intentionally safe to re-run: generated settings are only
# written when the development environment does not exist yet.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.dev.env"
DATA_DIR="${ROOT_DIR}/.dev/data"
COMPOSE_FILE="${ROOT_DIR}/deploy/docker-compose.dev.yml"
BACKEND_LOG="${ROOT_DIR}/.dev/backend.log"
FRONTEND_LOG="${ROOT_DIR}/.dev/frontend.log"
CADDY_LOG="${ROOT_DIR}/.dev/caddy.log"
CADDYFILE="${ROOT_DIR}/deploy/Caddyfile.dev"

info() { printf '\033[1;34m[dev]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[dev] error:\033[0m %s\n' "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "Docker is required for PostgreSQL and Redis."
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required (docker compose)."
command -v go >/dev/null 2>&1 || die "Go is required to run the backend."
command -v pnpm >/dev/null 2>&1 || die "pnpm is required to run the frontend."
command -v curl >/dev/null 2>&1 || die "curl is required for the backend readiness check."
command -v caddy >/dev/null 2>&1 || die "Caddy is required for local HTTPS. Install it with: brew install caddy"
command -v lsof >/dev/null 2>&1 || die "lsof is required to check local port conflicts."

mkdir -p "${ROOT_DIR}/.dev" "${DATA_DIR}" "${ROOT_DIR}/deploy/postgres_data" "${ROOT_DIR}/deploy/redis_data"

if [[ ! -f "${ENV_FILE}" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    DEV_PASSWORD="$(openssl rand -hex 20)"
    JWT_SECRET="$(openssl rand -hex 32)"
    TOTP_ENCRYPTION_KEY="$(openssl rand -hex 32)"
  else
    DEV_PASSWORD="sub2api-dev-password"
    JWT_SECRET="sub2api-dev-jwt-secret-change-me"
    TOTP_ENCRYPTION_KEY="000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
  fi
  cat >"${ENV_FILE}" <<EOF
# Generated by scripts/dev.sh. This file is local-only and gitignored.
POSTGRES_USER=sub2api
POSTGRES_PASSWORD=${DEV_PASSWORD}
POSTGRES_DB=sub2api
DATABASE_HOST_PORT=${DATABASE_HOST_PORT:-5432}
REDIS_HOST_PORT=${REDIS_HOST_PORT:-6379}
REDIS_PASSWORD=
ADMIN_EMAIL=${ADMIN_EMAIL:-admin@sub2api.local}
ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123456}
JWT_SECRET=${JWT_SECRET}
TOTP_ENCRYPTION_KEY=${TOTP_ENCRYPTION_KEY}
TZ=${TZ:-Asia/Shanghai}
EOF
  chmod 600 "${ENV_FILE}"
  info "Generated ${ENV_FILE} (admin: ${ADMIN_EMAIL:-admin@sub2api.local})"
fi

# Older .dev.env files may predate the fixed encryption key setting. Add one
# once so encrypted monitor/API credentials survive subsequent restarts.
if ! grep -q '^TOTP_ENCRYPTION_KEY=' "${ENV_FILE}"; then
  if command -v openssl >/dev/null 2>&1; then
    TOTP_ENCRYPTION_KEY="$(openssl rand -hex 32)"
  else
    TOTP_ENCRYPTION_KEY="000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
  fi
  printf '\nTOTP_ENCRYPTION_KEY=%s\n' "${TOTP_ENCRYPTION_KEY}" >>"${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  info "Added persistent TOTP_ENCRYPTION_KEY to ${ENV_FILE}"
fi

# Load values for the local backend. Existing shell variables take precedence.
set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

export DATA_DIR
export AUTO_SETUP=true
export CHANNEL_MONITOR_ALLOW_LOCAL_ENDPOINTS=true
export SERVER_HOST="${SERVER_HOST:-127.0.0.1}"
export SERVER_PORT="${SERVER_PORT:-8080}"
export FRONTEND_PORT="${FRONTEND_PORT:-3000}"
export SERVER_MODE="${SERVER_MODE:-debug}"
export DATABASE_HOST=127.0.0.1
export DATABASE_PORT="${DATABASE_HOST_PORT:-5432}"
export DATABASE_USER="${POSTGRES_USER:-sub2api}"
export DATABASE_PASSWORD="${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is missing from ${ENV_FILE}}"
export DATABASE_DBNAME="${POSTGRES_DB:-sub2api}"
export DATABASE_SSLMODE=disable
export REDIS_HOST=127.0.0.1
export REDIS_PORT="${REDIS_HOST_PORT:-6379}"
export REDIS_USERNAME="${REDIS_USERNAME:-}"
export REDIS_PASSWORD="${REDIS_PASSWORD:-}"
export REDIS_DB="${REDIS_DB:-0}"
export ADMIN_EMAIL="${ADMIN_EMAIL:-admin@sub2api.local}"
export ADMIN_PASSWORD="${ADMIN_PASSWORD:-admin123456}"
export JWT_SECRET="${JWT_SECRET:?JWT_SECRET is missing from ${ENV_FILE}}"
export TOTP_ENCRYPTION_KEY="${TOTP_ENCRYPTION_KEY:?TOTP_ENCRYPTION_KEY is missing from ${ENV_FILE}}"
export TZ="${TZ:-Asia/Shanghai}"
export VITE_DEV_PROXY_TARGET="http://${SERVER_HOST}:${SERVER_PORT}"

port_owner() {
  lsof -nP -tiTCP:"$1" -sTCP:LISTEN 2>/dev/null | paste -sd ',' - || true
}

stop_matching_processes() {
  local pattern="$1" pid command
  while read -r pid; do
    [[ -z "${pid}" ]] && continue
    command="$(ps -p "${pid}" -o command= 2>/dev/null || true)"
    [[ -z "${command}" ]] && continue
    info "Stopping stale development process ${pid}: ${command}"
    kill "${pid}" 2>/dev/null || true
  done < <(pgrep -f "${pattern}" 2>/dev/null || true)
}

stop_stale_dev_processes() {
  # Match only commands tied to this checkout. Other projects sharing a port
  # are left alone and reported by ensure_port_free below.
  stop_matching_processes "caddy run --config .*Caddyfile.dev"
  stop_matching_processes "${ROOT_DIR}/frontend/node_modules/.*/vite"
  stop_matching_processes "${ROOT_DIR}/backend.*go run ./cmd/server"
  # The `go run` parent command may not include the checkout path in `ps`.
  # These ports are dedicated to this dev stack, so clear any remaining
  # listeners before starting fresh child processes.
  for port in "${SERVER_PORT}" "${FRONTEND_PORT}" 8443; do
    while read -r pid; do
      [[ -z "${pid}" || "${pid}" == "$$" ]] && continue
      info "Stopping stale process ${pid} listening on port ${port}"
      kill "${pid}" 2>/dev/null || true
    done < <(lsof -nP -tiTCP:"${port}" -sTCP:LISTEN 2>/dev/null || true)
  done
  sleep 1
}

ensure_port_free() {
  local port="$1" label="$2" owner
  owner="$(port_owner "${port}")"
  [[ -z "${owner}" ]] && return 0
  die "${label} port ${port} is already in use (PID ${owner}). Stop that process or set another port."
}

cleanup() {
  trap - INT TERM EXIT
  [[ -n "${BACKEND_PID:-}" ]] && kill "${BACKEND_PID}" 2>/dev/null || true
  [[ -n "${FRONTEND_PID:-}" ]] && kill "${FRONTEND_PID}" 2>/dev/null || true
  [[ -n "${CADDY_PID:-}" ]] && kill "${CADDY_PID}" 2>/dev/null || true
}
trap cleanup INT TERM EXIT

info "Starting PostgreSQL and Redis..."
docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" up -d postgres redis
info "Waiting for database services..."
docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" up -d --wait postgres redis

stop_stale_dev_processes
ensure_port_free "${SERVER_PORT}" "Backend"
ensure_port_free "${FRONTEND_PORT}" "Frontend"
ensure_port_free 8443 "HTTPS"

info "Starting backend at http://${SERVER_HOST}:${SERVER_PORT}"
(cd "${ROOT_DIR}/backend" && go run ./cmd/server) >"${BACKEND_LOG}" 2>&1 &
BACKEND_PID=$!

for _ in {1..30}; do
  kill -0 "${BACKEND_PID}" 2>/dev/null || { tail -n 40 "${BACKEND_LOG}" >&2; die "Backend exited during startup."; }
  if curl -fsS "http://${SERVER_HOST}:${SERVER_PORT}/health" >/dev/null 2>&1; then break; fi
  sleep 1
done

info "Starting frontend at http://localhost:${FRONTEND_PORT}"
(cd "${ROOT_DIR}/frontend" && pnpm dev --host 0.0.0.0 --port "${FRONTEND_PORT}" --strictPort) >"${FRONTEND_LOG}" 2>&1 &
FRONTEND_PID=$!

info "Starting local HTTPS at https://sub2api.localhost:8443"
if ! caddy trust >/dev/null 2>&1; then
  info "Caddy CA trust setup needs permission; run 'caddy trust' once if the browser warns about the certificate."
fi
(cd "${ROOT_DIR}" && caddy run --config "${CADDYFILE}" --adapter caddyfile) >"${CADDY_LOG}" 2>&1 &
CADDY_PID=$!

info "Ready. Admin login: ${ADMIN_EMAIL} / ${ADMIN_PASSWORD}"
info "Monitor endpoint: https://sub2api.localhost:8443"
info "Logs: ${BACKEND_LOG}, ${FRONTEND_LOG}, and ${CADDY_LOG}"
info "Press Ctrl-C to stop the local backend/frontend (database containers remain running)."
wait "${BACKEND_PID}" "${FRONTEND_PID}"
