// Code generated by ent, DO NOT EDIT.

package admintelegrambinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the admintelegrambinding type in the database.
	Label = "admin_telegram_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAdminID holds the string denoting the admin_id field in the database.
	FieldAdminID = "admin_id"
	// FieldTelegramUserID holds the string denoting the telegram_user_id field in the database.
	FieldTelegramUserID = "telegram_user_id"
	// FieldChatID holds the string denoting the chat_id field in the database.
	FieldChatID = "chat_id"
	// FieldTelegramUsername holds the string denoting the telegram_username field in the database.
	FieldTelegramUsername = "telegram_username"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldNotifyNewTicket holds the string denoting the notify_new_ticket field in the database.
	FieldNotifyNewTicket = "notify_new_ticket"
	// FieldNotifyUserReply holds the string denoting the notify_user_reply field in the database.
	FieldNotifyUserReply = "notify_user_reply"
	// FieldNotifyHighPriority holds the string denoting the notify_high_priority field in the database.
	FieldNotifyHighPriority = "notify_high_priority"
	// FieldBoundAt holds the string denoting the bound_at field in the database.
	FieldBoundAt = "bound_at"
	// FieldLastSuccessAt holds the string denoting the last_success_at field in the database.
	FieldLastSuccessAt = "last_success_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the admintelegrambinding in the database.
	Table = "admin_telegram_bindings"
)

// Columns holds all SQL columns for admintelegrambinding fields.
var Columns = []string{
	FieldID,
	FieldAdminID,
	FieldTelegramUserID,
	FieldChatID,
	FieldTelegramUsername,
	FieldEnabled,
	FieldNotifyNewTicket,
	FieldNotifyUserReply,
	FieldNotifyHighPriority,
	FieldBoundAt,
	FieldLastSuccessAt,
	FieldLastError,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TelegramUsernameValidator is a validator for the "telegram_username" field. It is called by the builders before save.
	TelegramUsernameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultNotifyNewTicket holds the default value on creation for the "notify_new_ticket" field.
	DefaultNotifyNewTicket bool
	// DefaultNotifyUserReply holds the default value on creation for the "notify_user_reply" field.
	DefaultNotifyUserReply bool
	// DefaultNotifyHighPriority holds the default value on creation for the "notify_high_priority" field.
	DefaultNotifyHighPriority bool
	// DefaultBoundAt holds the default value on creation for the "bound_at" field.
	DefaultBoundAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the AdminTelegramBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAdminID orders the results by the admin_id field.
func ByAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminID, opts...).ToFunc()
}

// ByTelegramUserID orders the results by the telegram_user_id field.
func ByTelegramUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTelegramUserID, opts...).ToFunc()
}

// ByChatID orders the results by the chat_id field.
func ByChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatID, opts...).ToFunc()
}

// ByTelegramUsername orders the results by the telegram_username field.
func ByTelegramUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTelegramUsername, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByNotifyNewTicket orders the results by the notify_new_ticket field.
func ByNotifyNewTicket(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyNewTicket, opts...).ToFunc()
}

// ByNotifyUserReply orders the results by the notify_user_reply field.
func ByNotifyUserReply(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyUserReply, opts...).ToFunc()
}

// ByNotifyHighPriority orders the results by the notify_high_priority field.
func ByNotifyHighPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyHighPriority, opts...).ToFunc()
}

// ByBoundAt orders the results by the bound_at field.
func ByBoundAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoundAt, opts...).ToFunc()
}

// ByLastSuccessAt orders the results by the last_success_at field.
func ByLastSuccessAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSuccessAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
