// Code generated by ent, DO NOT EDIT.

package admintelegrambinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLTE(FieldID, id))
}

// AdminID applies equality check predicate on the "admin_id" field. It's identical to AdminIDEQ.
func AdminID(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldAdminID, v))
}

// TelegramUserID applies equality check predicate on the "telegram_user_id" field. It's identical to TelegramUserIDEQ.
func TelegramUserID(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldTelegramUserID, v))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldChatID, v))
}

// TelegramUsername applies equality check predicate on the "telegram_username" field. It's identical to TelegramUsernameEQ.
func TelegramUsername(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldTelegramUsername, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldEnabled, v))
}

// NotifyNewTicket applies equality check predicate on the "notify_new_ticket" field. It's identical to NotifyNewTicketEQ.
func NotifyNewTicket(v bool) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldNotifyNewTicket, v))
}

// NotifyUserReply applies equality check predicate on the "notify_user_reply" field. It's identical to NotifyUserReplyEQ.
func NotifyUserReply(v bool) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldNotifyUserReply, v))
}

// NotifyHighPriority applies equality check predicate on the "notify_high_priority" field. It's identical to NotifyHighPriorityEQ.
func NotifyHighPriority(v bool) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldNotifyHighPriority, v))
}

// BoundAt applies equality check predicate on the "bound_at" field. It's identical to BoundAtEQ.
func BoundAt(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldBoundAt, v))
}

// LastSuccessAt applies equality check predicate on the "last_success_at" field. It's identical to LastSuccessAtEQ.
func LastSuccessAt(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldLastError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// AdminIDEQ applies the EQ predicate on the "admin_id" field.
func AdminIDEQ(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldAdminID, v))
}

// AdminIDNEQ applies the NEQ predicate on the "admin_id" field.
func AdminIDNEQ(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldAdminID, v))
}

// AdminIDIn applies the In predicate on the "admin_id" field.
func AdminIDIn(vs ...int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIn(FieldAdminID, vs...))
}

// AdminIDNotIn applies the NotIn predicate on the "admin_id" field.
func AdminIDNotIn(vs ...int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotIn(FieldAdminID, vs...))
}

// AdminIDGT applies the GT predicate on the "admin_id" field.
func AdminIDGT(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGT(FieldAdminID, v))
}

// AdminIDGTE applies the GTE predicate on the "admin_id" field.
func AdminIDGTE(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGTE(FieldAdminID, v))
}

// AdminIDLT applies the LT predicate on the "admin_id" field.
func AdminIDLT(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLT(FieldAdminID, v))
}

// AdminIDLTE applies the LTE predicate on the "admin_id" field.
func AdminIDLTE(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLTE(FieldAdminID, v))
}

// TelegramUserIDEQ applies the EQ predicate on the "telegram_user_id" field.
func TelegramUserIDEQ(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldTelegramUserID, v))
}

// TelegramUserIDNEQ applies the NEQ predicate on the "telegram_user_id" field.
func TelegramUserIDNEQ(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldTelegramUserID, v))
}

// TelegramUserIDIn applies the In predicate on the "telegram_user_id" field.
func TelegramUserIDIn(vs ...int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIn(FieldTelegramUserID, vs...))
}

// TelegramUserIDNotIn applies the NotIn predicate on the "telegram_user_id" field.
func TelegramUserIDNotIn(vs ...int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotIn(FieldTelegramUserID, vs...))
}

// TelegramUserIDGT applies the GT predicate on the "telegram_user_id" field.
func TelegramUserIDGT(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGT(FieldTelegramUserID, v))
}

// TelegramUserIDGTE applies the GTE predicate on the "telegram_user_id" field.
func TelegramUserIDGTE(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGTE(FieldTelegramUserID, v))
}

// TelegramUserIDLT applies the LT predicate on the "telegram_user_id" field.
func TelegramUserIDLT(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLT(FieldTelegramUserID, v))
}

// TelegramUserIDLTE applies the LTE predicate on the "telegram_user_id" field.
func TelegramUserIDLTE(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLTE(FieldTelegramUserID, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotIn(FieldChatID, vs...))
}

// ChatIDGT applies the GT predicate on the "chat_id" field.
func ChatIDGT(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGT(FieldChatID, v))
}

// ChatIDGTE applies the GTE predicate on the "chat_id" field.
func ChatIDGTE(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGTE(FieldChatID, v))
}

// ChatIDLT applies the LT predicate on the "chat_id" field.
func ChatIDLT(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLT(FieldChatID, v))
}

// ChatIDLTE applies the LTE predicate on the "chat_id" field.
func ChatIDLTE(v int64) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLTE(FieldChatID, v))
}

// TelegramUsernameEQ applies the EQ predicate on the "telegram_username" field.
func TelegramUsernameEQ(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldTelegramUsername, v))
}

// TelegramUsernameNEQ applies the NEQ predicate on the "telegram_username" field.
func TelegramUsernameNEQ(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldTelegramUsername, v))
}

// TelegramUsernameIn applies the In predicate on the "telegram_username" field.
func TelegramUsernameIn(vs ...string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIn(FieldTelegramUsername, vs...))
}

// TelegramUsernameNotIn applies the NotIn predicate on the "telegram_username" field.
func TelegramUsernameNotIn(vs ...string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotIn(FieldTelegramUsername, vs...))
}

// TelegramUsernameGT applies the GT predicate on the "telegram_username" field.
func TelegramUsernameGT(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGT(FieldTelegramUsername, v))
}

// TelegramUsernameGTE applies the GTE predicate on the "telegram_username" field.
func TelegramUsernameGTE(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGTE(FieldTelegramUsername, v))
}

// TelegramUsernameLT applies the LT predicate on the "telegram_username" field.
func TelegramUsernameLT(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLT(FieldTelegramUsername, v))
}

// TelegramUsernameLTE applies the LTE predicate on the "telegram_username" field.
func TelegramUsernameLTE(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLTE(FieldTelegramUsername, v))
}

// TelegramUsernameContains applies the Contains predicate on the "telegram_username" field.
func TelegramUsernameContains(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldContains(FieldTelegramUsername, v))
}

// TelegramUsernameHasPrefix applies the HasPrefix predicate on the "telegram_username" field.
func TelegramUsernameHasPrefix(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldHasPrefix(FieldTelegramUsername, v))
}

// TelegramUsernameHasSuffix applies the HasSuffix predicate on the "telegram_username" field.
func TelegramUsernameHasSuffix(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldHasSuffix(FieldTelegramUsername, v))
}

// TelegramUsernameIsNil applies the IsNil predicate on the "telegram_username" field.
func TelegramUsernameIsNil() predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIsNull(FieldTelegramUsername))
}

// TelegramUsernameNotNil applies the NotNil predicate on the "telegram_username" field.
func TelegramUsernameNotNil() predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotNull(FieldTelegramUsername))
}

// TelegramUsernameEqualFold applies the EqualFold predicate on the "telegram_username" field.
func TelegramUsernameEqualFold(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEqualFold(FieldTelegramUsername, v))
}

// TelegramUsernameContainsFold applies the ContainsFold predicate on the "telegram_username" field.
func TelegramUsernameContainsFold(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldContainsFold(FieldTelegramUsername, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldEnabled, v))
}

// NotifyNewTicketEQ applies the EQ predicate on the "notify_new_ticket" field.
func NotifyNewTicketEQ(v bool) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldNotifyNewTicket, v))
}

// NotifyNewTicketNEQ applies the NEQ predicate on the "notify_new_ticket" field.
func NotifyNewTicketNEQ(v bool) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldNotifyNewTicket, v))
}

// NotifyUserReplyEQ applies the EQ predicate on the "notify_user_reply" field.
func NotifyUserReplyEQ(v bool) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldNotifyUserReply, v))
}

// NotifyUserReplyNEQ applies the NEQ predicate on the "notify_user_reply" field.
func NotifyUserReplyNEQ(v bool) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldNotifyUserReply, v))
}

// NotifyHighPriorityEQ applies the EQ predicate on the "notify_high_priority" field.
func NotifyHighPriorityEQ(v bool) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldNotifyHighPriority, v))
}

// NotifyHighPriorityNEQ applies the NEQ predicate on the "notify_high_priority" field.
func NotifyHighPriorityNEQ(v bool) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldNotifyHighPriority, v))
}

// BoundAtEQ applies the EQ predicate on the "bound_at" field.
func BoundAtEQ(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldBoundAt, v))
}

// BoundAtNEQ applies the NEQ predicate on the "bound_at" field.
func BoundAtNEQ(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldBoundAt, v))
}

// BoundAtIn applies the In predicate on the "bound_at" field.
func BoundAtIn(vs ...time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIn(FieldBoundAt, vs...))
}

// BoundAtNotIn applies the NotIn predicate on the "bound_at" field.
func BoundAtNotIn(vs ...time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotIn(FieldBoundAt, vs...))
}

// BoundAtGT applies the GT predicate on the "bound_at" field.
func BoundAtGT(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGT(FieldBoundAt, v))
}

// BoundAtGTE applies the GTE predicate on the "bound_at" field.
func BoundAtGTE(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGTE(FieldBoundAt, v))
}

// BoundAtLT applies the LT predicate on the "bound_at" field.
func BoundAtLT(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLT(FieldBoundAt, v))
}

// BoundAtLTE applies the LTE predicate on the "bound_at" field.
func BoundAtLTE(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLTE(FieldBoundAt, v))
}

// LastSuccessAtEQ applies the EQ predicate on the "last_success_at" field.
func LastSuccessAtEQ(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtNEQ applies the NEQ predicate on the "last_success_at" field.
func LastSuccessAtNEQ(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtIn applies the In predicate on the "last_success_at" field.
func LastSuccessAtIn(vs ...time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtNotIn applies the NotIn predicate on the "last_success_at" field.
func LastSuccessAtNotIn(vs ...time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtGT applies the GT predicate on the "last_success_at" field.
func LastSuccessAtGT(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGT(FieldLastSuccessAt, v))
}

// LastSuccessAtGTE applies the GTE predicate on the "last_success_at" field.
func LastSuccessAtGTE(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGTE(FieldLastSuccessAt, v))
}

// LastSuccessAtLT applies the LT predicate on the "last_success_at" field.
func LastSuccessAtLT(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLT(FieldLastSuccessAt, v))
}

// LastSuccessAtLTE applies the LTE predicate on the "last_success_at" field.
func LastSuccessAtLTE(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLTE(FieldLastSuccessAt, v))
}

// LastSuccessAtIsNil applies the IsNil predicate on the "last_success_at" field.
func LastSuccessAtIsNil() predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIsNull(FieldLastSuccessAt))
}

// LastSuccessAtNotNil applies the NotNil predicate on the "last_success_at" field.
func LastSuccessAtNotNil() predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotNull(FieldLastSuccessAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldContainsFold(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminTelegramBinding) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminTelegramBinding) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminTelegramBinding) predicate.AdminTelegramBinding {
	return predicate.AdminTelegramBinding(sql.NotPredicates(p))
}
